### ISSUE TITLE
exabgp.env not found in a virtualenv

### ISSUE THREAD

**Issue by fobser** [Exa-Networks/exabgp#254] opened 2015-05-08 14:00 UTC
Say I have an /opt/exabgp virtualenv and exabgp.env is sitting in /opt/exabgp/etc/exabgp.env.
On 3.4.10 does not find that file:
> (exabgp)[root@rrc ~]# /opt/exabgp/bin/exabgp /opt/exabgp/etc/exabgp/exabgp_foo.conf
> Fri, 08 May 2015 13:31:32 | INFO     | 1412   | configuration | environment file missing
> Fri, 08 May 2015 13:31:32 | INFO     | 1412   | configuration | generate it using "exabgp --fi > /etc/exabgp/exabgp.env"
> Fri, 08 May 2015 13:31:32 | INFO     | 1412   | reactor       | Performing reload of exabgp 3.4.10
This used to work on 3.4.5

Maybe https://github.com/Exa-Networks/exabgp/issues/253 is related.

**Comment by thomas-mangin** [comment] 2015-05-08 16:37
Could you please run exabgp under strace and grep -B10 -A10 'exabgp.env' so I can see what env file your installation is trying to open ?

**Comment by thomas-mangin** [comment] 2015-05-13 13:05
ok - I was surprised to find exabgp in bin and not sbin. I assume you installed exabgp in /opt/exabgp with pip. ExaBGP hardcode the location it is looking in .

The env folder can be specified with the --env command line option if you do not want your configuration file in /etc/exabgp/ but /opt/exabgp

I may review how I lookup the folder ( in bgp.py line 61+ ) but more information would be welcome on how this was installed please.

**Comment by fobser** [comment] 2015-05-13 15:13
Oops sorry, forgot to let you know. I'm very busy this week and
can't work on exabgp. I hope I can provide more information
next week and test the counter fix as well

**Comment by thomas-mangin** [comment] 2015-05-13 15:15
No issue at all, thank you for letting me know.

**Comment by thomas-mangin** [comment] 2015-05-14 12:07
@fobser you have a very "interesting" installation.

when using the code from a tarball / git from opt, the path of exabgp should be `/opt/exabgp/sbin/exabgp` , note that it should be sbin

As your command line is `/opt/exabgp/bin/exabgp /opt/exabgp/etc/exabgp/exabgp_foo.conf` it looks like the program was installed by pip in /opt/exabgp ( and not /opt directly )

This seems to be confirmed by the fact that your configuration file is `/opt/exabgp/etc/exabgp/exabgp_foo.conf` 

Up to now ExaBGP would only seek its configuration file in:
 - using the `ENV` environment variable
 - the `--env` configuration file was indicating.
 - `/usr/local/etc/exabgp` if the program was installed in `/usr/local` 

This should be all fixed by this patch 747026f

**Closed** 2015-05-23 16:28 UTC
Labels: bug, fixed-need-testing

**Comment by fobser** [comment] 2015-05-26 10:02
Finally got around testing this. Yes, this works now.
The setup is this:
* git clone https://github.com/Exa-Networks/exabgp.git
* (cd exabgp && tar czf ../exabgp-3.10.tar.gz *)
* pip wheel ./exabgp-3.10.tar.gz
* virtualenv /opt/exabgp
* source /opt/exabgp/bin/activate
* pip install exabgp-3.4.10-py2-none-any.whl
and with that I get /opt/exabgp/bin/exabgp (bin, not sbin), don't know why this happens.
(I typed the commands from off the top of my head, there might be typos in there. I create the wheel on OS X, the virtualenv is on centos 6)

**Comment by thomas-mangin** [comment] 2015-05-26 10:32
Thank you :-)

**Comment by thomas-mangin** [comment] 2015-05-26 10:33
The code goes in bin because it is where pip install programs ( there is no distinctions between daemon and utilities ). I may look at changing this in 3.5
