### ISSUE TITLE
Traceback in logs

### ISSUE THREAD

**Issue by spakka** [Exa-Networks/exabgp#549] opened 2016-12-08 13:38 UTC
Hi,

We see these occasionally:
```
Dec  6 11:51:41 rrc19 exabgp: 7917   network       Connected to peer neighbor 196.46.25.133 local-ip 196.46.25.86 local-as 12654 peer-as 8075 router-id 196.46.25.86 family-allowed in-open (out)
Dec  6 11:51:45 rrc19 exabgp: 7917   network       Connected to peer neighbor 2001:43f8:6d0::133 local-ip 2001:43f8:6d0::86 local-as 12654 peer-as 8075 router-id 196.46.25.86 family-allowed in-open (out)
Dec  6 11:57:01 rrc19 exabgp: 7917   network       Peer   196.46.25.133 ASN 8075    out loop, peer reset, message [] error[]
Dec  6 11:57:01 rrc19 exabgp: 7917   network       Peer 2001:43f8:6d0::133 ASN 8075    out loop, peer reset, message [] error[]
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19 EXABGP MISBEHAVED / HELP US FIX IT
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 Sorry, you encountered a problem with ExaBGP, as the problem only affects one
Dec  6 11:57:01 rrc19 peer, we are trying to keep the program running.
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 There are a few things you can do to help us (and yourself):
Dec  6 11:57:01 rrc19 - make sure you are running the latest version of the code available at
Dec  6 11:57:01 rrc19   https://github.com/Exa-Networks/exabgp/releases/latest
Dec  6 11:57:01 rrc19 - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
Dec  6 11:57:01 rrc19   so it can be fixed (github can be searched for similar reports)
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 PLEASE, when reporting, do include as much information as you can:
Dec  6 11:57:01 rrc19 - do not obfuscate any data (feel free to send us a private  email with the
Dec  6 11:57:01 rrc19   extra information if your business policy is strict on information sharing)
Dec  6 11:57:01 rrc19   https://github.com/Exa-Networks/exabgp/wiki/FAQ
Dec  6 11:57:01 rrc19 - if you can reproduce the issue, run ExaBGP with the command line option -d
Dec  6 11:57:01 rrc19   it provides us with much needed information to fix problems quickly
Dec  6 11:57:01 rrc19 - include the information presented below
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 Should you not receive an acknowledgment of your issue on github (assignement,
Dec  6 11:57:01 rrc19 comment, or similar) within a few hours, feel free to email us to make sure
Dec  6 11:57:01 rrc19 it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19 -- Please provide ALL the information below on :
Dec  6 11:57:01 rrc19 -- https://github.com/Exa-Networks/exabgp/issues
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 ExaBGP version : 3.4.15
Dec  6 11:57:01 rrc19 Python version : 2.7.3 (f66246c46ca30b26a5c73e4cc95dd6235c966b8f, Jul 30 2013, 09:27:06) [PyPy 2.0.2 with GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
Dec  6 11:57:01 rrc19 System Uname   : #1 SMP Wed Oct 5 00:36:12 UTC 2016
Dec  6 11:57:01 rrc19 System MaxInt  : 9223372036854775807
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 peer 196.46.25.133 ASN 8075
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 <type 'exceptions.KeyError'>
Dec  6 11:57:01 rrc19 3
Dec  6 11:57:01 rrc19 Traceback (most recent call last):
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/peer.py", line 587, in _run
Dec  6 11:57:01 rrc19     for action in self._main(direction):
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/peer.py", line 456, in _main
Dec  6 11:57:01 rrc19     for message in proto.read_message():
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/protocol.py", line 173, in read_message
Dec  6 11:57:01 rrc19     self.peer.reactor.processes.message(msg_id,self.peer,message,header,body)
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/api/processes.py", line 270, in closure
Dec  6 11:57:01 rrc19     return function(self,*args)
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/api/processes.py", line 306, in message
Dec  6 11:57:01 rrc19     self._dispatch[message_id](self,peer,message,header,*body)
Dec  6 11:57:01 rrc19 KeyError: 3
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19 -- Please provide _ALL_ the information above on :
Dec  6 11:57:01 rrc19 -- https://github.com/Exa-Networks/exabgp/issues
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19 EXABGP MISBEHAVED / HELP US FIX IT
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 Sorry, you encountered a problem with ExaBGP, as the problem only affects one
Dec  6 11:57:01 rrc19 peer, we are trying to keep the program running.
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 There are a few things you can do to help us (and yourself):
Dec  6 11:57:01 rrc19 - make sure you are running the latest version of the code available at
Dec  6 11:57:01 rrc19   https://github.com/Exa-Networks/exabgp/releases/latest
Dec  6 11:57:01 rrc19 - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
Dec  6 11:57:01 rrc19   so it can be fixed (github can be searched for similar reports)
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 PLEASE, when reporting, do include as much information as you can:
Dec  6 11:57:01 rrc19 - do not obfuscate any data (feel free to send us a private  email with the
Dec  6 11:57:01 rrc19   extra information if your business policy is strict on information sharing)
Dec  6 11:57:01 rrc19   https://github.com/Exa-Networks/exabgp/wiki/FAQ
Dec  6 11:57:01 rrc19 - if you can reproduce the issue, run ExaBGP with the command line option -d
Dec  6 11:57:01 rrc19   it provides us with much needed information to fix problems quickly
Dec  6 11:57:01 rrc19 - include the information presented below
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 Should you not receive an acknowledgment of your issue on github (assignement,
Dec  6 11:57:01 rrc19 comment, or similar) within a few hours, feel free to email us to make sure
Dec  6 11:57:01 rrc19 it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19 -- Please provide ALL the information below on :
Dec  6 11:57:01 rrc19 -- https://github.com/Exa-Networks/exabgp/issues
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 ExaBGP version : 3.4.15
Dec  6 11:57:01 rrc19 Python version : 2.7.3 (f66246c46ca30b26a5c73e4cc95dd6235c966b8f, Jul 30 2013, 09:27:06) [PyPy 2.0.2 with GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
Dec  6 11:57:01 rrc19 System Uname   : #1 SMP Wed Oct 5 00:36:12 UTC 2016
Dec  6 11:57:01 rrc19 System MaxInt  : 9223372036854775807
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 peer 2001:43f8:6d0::133 ASN 8075
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 <type 'exceptions.KeyError'>
Dec  6 11:57:01 rrc19 3
Dec  6 11:57:01 rrc19 Traceback (most recent call last):
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/peer.py", line 587, in _run
Dec  6 11:57:01 rrc19     for action in self._main(direction):
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/peer.py", line 456, in _main
Dec  6 11:57:01 rrc19     for message in proto.read_message():
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/protocol.py", line 173, in read_message
Dec  6 11:57:01 rrc19     self.peer.reactor.processes.message(msg_id,self.peer,message,header,body)
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/api/processes.py", line 270, in closure
Dec  6 11:57:01 rrc19     return function(self,*args)
Dec  6 11:57:01 rrc19   File "/opt/exabgp/site-packages/exabgp/reactor/api/processes.py", line 306, in message
Dec  6 11:57:01 rrc19     self._dispatch[message_id](self,peer,message,header,*body)
Dec  6 11:57:01 rrc19 KeyError: 3
Dec  6 11:57:01 rrc19
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19 -- Please provide _ALL_ the information above on :
Dec  6 11:57:01 rrc19 -- https://github.com/Exa-Networks/exabgp/issues
Dec  6 11:57:01 rrc19 ********************************************************************************
Dec  6 11:57:01 rrc19
Dec  6 11:58:05 rrc19 exabgp: 7917   network       Connected to peer neighbor 2001:43f8:6d0::133 local-ip 2001:43f8:6d0::86 local-as 12654 peer-as 8075 router-id 196.46.25.86 family-allowed in-open (out)
Dec  6 11:58:05 rrc19 exabgp: 7917   network       Connected to peer neighbor 196.46.25.133 local-ip 196.46.25.86 local-as 12654 peer-as 8075 router-id 196.46.25.86 family-allowed in-open (out)
```

Reporting this as requested :) If you need any more info, just let me know.

Cheers
Colin

**Comment by thomas-mangin** [comment] 2016-12-13 18:05
This is an extremely weird issue as AFAIU my own code, it should be impossible ...

**Comment by thomas-mangin** [comment] 2017-01-06 19:21
Sorry for the delay - not ignoring the issue ..

**Comment by thomas-mangin** [comment] 2017-03-04 16:36
The issue is resolved in more recent release. The code which register events for NOTIFICATION was missing. I can not easily track the patch but the line was (more code may be required tho for it to work).

```
    @register_process(Message.CODE.NOTIFICATION,_dispatch)
    def _notification (self, peer, message, header, body):
        for process in self._notify(peer,'receive-notifications'):
             self.write(process,self._encoder[process].notification(peer,message.code,message.subcode,body),peer)
```

Once again, sorry for the long time.

**Closed** 2017-03-04 16:36 UTC
Labels: bug
