### ISSUE TITLE
Extraneous address family added to peers after the first one configured.

### ISSUE THREAD

**Issue by asahi-eric** [Exa-Networks/exabgp#826] opened 2018-06-11 02:37 UTC
##### Summary

4 peers configured, 2 of IPv4 only and 2 of IPv6 only, order is IPv4 peer, IPv6 peer, IPv4 peer, IPv6 peer.  Each peer is only configured for their respective address family but only the first peer configured in the config file adheres to that.   The remaining 3 try to use both address families.  Doing an `exabgpcli show neighbor configuration` shows that the 3 of the peers are configured for both address families.

##### OS
```
Linux Ubuntu 16.04.04 LTS
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
Linux exabgp1 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### Version
```
ExaBGP : 4.0.6-daa3d6ba
Python : 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Uname  : Linux exabpg1 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64
Root   : /usr/share/exabgp1/exabgp
```

##### Installation
```
Custom fabric with pip3 install of whl
```

##### Environment 
```
empty
```

##### Configuration

Sanitized config.

```
process **** {
    run ****;
    encoder json;
}

neighbor 1.2.3.1 {
    router-id 1.2.3.4;
    local-address 1.2.3.4;
    local-as 64530;
    peer-as 64000;
    group-updates true;
    api {
        processes [ **** ];
        receive {
            parsed;
            update;
        }
        neighbor-changes;
    }
    family {
        ipv4 unicast;
    }
}
neighbor aaaa:bbbb:cccc:dddd::1 {
    router-id 1.2.3.4;
    local-address aaaa:bbbb:cccc:dddd::4;
    local-as 64530;
    peer-as 64000;
    group-updates true;
    api {
        processes [ **** ];
        receive {
            parsed;
            update;
        }
        neighbor-changes;
    }
    family {
        ipv6 unicast;
    }
}
neighbor 1.2.3.2 {
    router-id 1.2.3.4;
    local-address 1.2.3.4;
    local-as 64530;
    peer-as 64000;
    group-updates true;
    api {
        processes [ **** ];
        receive {
            parsed;
            update;
        }
        neighbor-changes;
    }
    family {
        ipv4 unicast;
    }
}
neighbor aaaa:bbbb:cccc:dddd::2 {
    router-id 1.2.3.4;
    local-address aaaa:bbbb:cccc:dddd::4;
    local-as 64530;
    peer-as 64000;
    group-updates true;
    api {
        processes [ **** ];
        receive {
            parsed;
            update;
        }
        neighbor-changes;
    }
    family {
        ipv6 unicast;
    }
}
```

##### Program output
Output sanitized.
```
neighbor 1.2.3.2 {
  description "";
  router-id 1.2.3.4;
  host-name exabgp1;
  domain-name exabgp1;
  local-address 1.2.3.4;
  local-as 64530;
  peer-as 64000;
  hold-time 180;
  manual-eor false;

  passive false;
  group-updates true;
  auto-flush true;
  adj-rib-in true;
  adj-rib-out true;
  md5-base64 auto;
  md5-ip "1.2.3.4";

  capability {
    asn4 enable;
    route-refresh disable;
    graceful-restart disable;
    add-path disable;
    multi-session disable;
    operational disable;
    aigp disable;
  }
  family {
    ipv4 unicast;
    ipv6 unicast;
  }
  add-path {
  }
  api {
    processes [ **** ];
    neighbor-changes;
    receive {
      parsed;
      update;
    }
  }
}
neighbor aaaa:bbbb:cccc:dddd::2 {
  description "";
  router-id 1.2.3.4;
  host-name exabgp1;
  domain-name exabgp1;
  local-address aaaa:bbbb:cccc:dddd::4;
  local-as 64530;
  peer-as 64000;
  hold-time 180;
  manual-eor false;

  passive false;
  group-updates true;
  auto-flush true;
  adj-rib-in true;
  adj-rib-out true;
  md5-base64 auto;
  md5-ip "aaaa:bbbb:cccc:dddd::4";

  capability {
    asn4 enable;
    route-refresh disable;
    graceful-restart disable;
    add-path disable;
    multi-session disable;
    operational disable;
    aigp disable;
  }
  family {
    ipv4 unicast;
    ipv6 unicast;
  }
  add-path {
  }
  api {
    processes [ **** ];
    neighbor-changes;
    receive {
      parsed;
      update;
    }
  }
}
neighbor aaaa:bbbb:cccc:dddd::1 {
  description "";
  router-id 1.2.3.4;
  host-name exabgp1;
  domain-name exabgp1;
  local-address aaaa:bbbb:cccc:dddd::4;
  local-as 64530;
  peer-as 64000;
  hold-time 180;
  manual-eor false;

  passive false;
  group-updates true;
  auto-flush true;
  adj-rib-in true;
  adj-rib-out true;
  md5-base64 auto;
  md5-ip "aaaa:bbbb:cccc:dddd::4";

  capability {
    asn4 enable;
    route-refresh disable;
    graceful-restart disable;
    add-path disable;
    multi-session disable;
    operational disable;
    aigp disable;
  }
  family {
    ipv4 unicast;
    ipv6 unicast;
  }
  add-path {
  }
  api {
    processes [ **** ];
    neighbor-changes;
    receive {
      parsed;
      update;
    }
  }
}
neighbor 1.2.3.1 {
  description "";
  router-id 1.2.3.4;
  host-name exabgp1;
  domain-name exabgp1;
  local-address 1.2.3.4;
  local-as 64530;
  peer-as 64000;
  hold-time 180;
  manual-eor false;

  passive false;
  group-updates true;
  auto-flush true;
  adj-rib-in true;
  adj-rib-out true;
  md5-base64 auto;
  md5-ip "1.2.3.4";

  capability {
    asn4 enable;
    route-refresh disable;
    graceful-restart disable;
    add-path disable;
    multi-session disable;
    operational disable;
    aigp disable;
  }
  family {
    ipv4 unicast;
  }
  add-path {
  }
  api {
    processes [ **** ];
    neighbor-changes;
    receive {
      parsed;
      update;
    }
  }
}
```

##### Steps to reproduce
```

```

##### Importance
The peer of the exabgp is configured only for a single address family, there are error logs pertaining to this
```
Jun 11 11:01:57 host exabgp[7257]: 11:01:57 | 7257   | configuration   | the route family is not configured on neighbor
```

**Comment by thomas-mangin** [comment] 2018-06-11 10:28
Not sure how the IPv6 family could "appear" on the peer 1.2.3.2

The the addition of IPv4 to the family: this is not a bug. IPv4 can not be disabled on a session. It is always valid to send IPv4 Unicast. So it does not matter if the capability is announced or not.

Last time I removed this explicit IPv4 - some users complained. If you think I am wrong please help me with the RFC.

**Comment by asahi-eric** [comment] 2018-06-12 02:56
I understand about having the default being to enable the IPv4 address family but it would be nice to have the option to explicitly disable this on a per peer basis.  I will try looking through the RFC's on this issue.

Anything else you need from me regarding how the IPv6 address family is still enabled on the 1.2.3.2 peer?

**Comment by martintopholm** [comment] 2019-03-15 13:40
I'm also seeing this. I have three peers in a [configuration](https://github.com/Exa-Networks/exabgp/files/2971291/example-config.txt) file:

    neighbor 192.0.2.136 { ... family ipv4 unicast; ...}
    neighbor 2001:db8:1:1:: { ... family ipv6 unicast; ...}
    neighbor 203.0.113.8 { ... family ipv4 unicast; ...}

The first is correctly announcing "ipv4 unicast".
The second one announces "ipv4 unicast and ipv6 unicast".
The last announces "ipv4 unicast and ipv6 unicast".

This causes a lot of noise on our Juniper routers:

    rpd[5337]: BGP_NLRI_MISMATCH: bgp_process_caps:
        mismatch NLRI with 203.0.113.9 (External AS 64601):
        peer: <inet-unicast inet6-unicast>(17) us: <inet-unicast>(1)

I've experimented with a [fix](https://github.com/martintopholm/exabgp/tree/issue-826), but don't understand the exabgp parser enough for this to be used unvalidated.

**Comment by thomas-mangin** [comment] 2019-05-12 13:16
The patch was modified (as it was not the right solution but had rightly identified the root cause). Now fixed with https://github.com/Exa-Networks/exabgp/commit/7bb4c7ea18725c08a8a41a7c75d24901f56566b4

**Closed by thomas-mangin** 2019-05-12 13:17 UTC
Labels: bug
