### ISSUE TITLE
the route family is not configured on neighbor

### ISSUE THREAD

**Issue by linecolumn** [Exa-Networks/exabgp#1023] opened 2021-02-09 19:05 UTC
Everything is working as planned, but ExaBGP logs are constantly filling with `the route family is not configured on neighbor`. This started to happen when I added IPv6 neighbors into the picture.

On the other side are Junipers with following configuration:

```
group SRV-TEST {
    type internal;
    multipath;
    neighbor 192.168.150.22 {           
        local-as 65000;                 
        bfd-liveness-detection {        
            minimum-interval 300;       
            multiplier 3;               
        }                               
    }
```

Below are all configuration:

```

Tue, 09 Feb 2021 18:48:58 1432305 configuration the route family is not configured on neighbor
Tue, 09 Feb 2021 18:48:58 1432305 configuration the route family is not configured on neighbor
Tue, 09 Feb 2021 18:48:58 1432305 api           route added to neighbor 192.168.150.5 local-ip 192.168.150.22 local-as 65000 peer-as 65000 router-id 192.168.150.22 family-allowed in-open, neighbor 2111:ff:XXXX::5 local-ip 2111:ff:XXXX::22 local-as 65000 peer-as 65000 router-id 192.168.150.22 family-allowed in-open, neighbor 192.168.150.4 local-ip 192.168.150.22 local-as 65000 peer-as 65000 router-id 192.168.150.22 family-allowed in-open, neighbor 2111:ff:XXXX::4 local-ip 2111:ff:XXXX::22 local-as 65000 peer-as 65000 router-id 192.168.150.22 family-allowed in-open : 2111:ff:XXXX::7/128 next-hop self med 100

$ exabgpcli show neighbor summary
Peer            AS        up/down state       |     #sent     #recvd
192.168.150.5   65000     0:09:53 established           3          1
2111:ff:XXXX::5 65000     0:09:53 established           2          1
2111:ff:XXXX::4 65000     0:09:53 established           2          1
192.168.150.4   65000     0:09:53 established           3          1

Neighbor 192.168.150.5

  Session                         Local
   local                 192.168.150.22                                
   state                    ESTABLISHED                                
   up for                       0:10:10                                

  Setup                           Local          Remote
   AS                             65000           65000                
   ID                    192.168.150.22  192.168.150.22                
   hold-time                          6              90                

  Capability                      Local          Remote
   asn4:                        enabled         enabled                
   route-refresh:              disabled         enabled                
   multi-session:              disabled        disabled                
   operational:                disabled        disabled                
   add-path:                   disabled        disabled                
   extended-message:            enabled        disabled                
   graceful-restart:           disabled         enabled                

  Families                        Local          Remote        Add-Path
   ipv4 unicast:                enabled         enabled        disabled

  Message Statistic                Sent        Received
   open:                              1               1                
   notification:                      0               0                
   keepalive:                       306             332                
   update:                            3               1                
   refresh:                           0               0                
   total:                           310             334                

Neighbor 2111:ff:XXXX::5

  Session                         Local
   local                2111:ff:XXXX::22                                
   state                    ESTABLISHED                                
   up for                       0:10:10                                

  Setup                           Local          Remote
   AS                             65000           65000                
   ID                    192.168.150.22  192.168.150.22                
   hold-time                          6              90                

  Capability                      Local          Remote
   asn4:                        enabled         enabled                
   route-refresh:              disabled         enabled                
   multi-session:              disabled        disabled                
   operational:                disabled        disabled                
   add-path:                   disabled        disabled                
   extended-message:            enabled        disabled                
   graceful-restart:           disabled         enabled                

  Families                        Local          Remote        Add-Path
   ipv6 unicast:                enabled         enabled        disabled

  Message Statistic                Sent        Received
   open:                              1               1                
   notification:                      0               0                
   keepalive:                       306             332                
   update:                            2               1                
   refresh:                           0               0                
   total:                           309             334                

Neighbor 192.168.150.4

  Session                         Local
   local                 192.168.150.22                                
   state                    ESTABLISHED                                
   up for                       0:10:10                                

  Setup                           Local          Remote
   AS                             65000           65000                
   ID                    192.168.150.22  192.168.150.22                
   hold-time                          6              90                

  Capability                      Local          Remote
   asn4:                        enabled         enabled                
   route-refresh:              disabled         enabled                
   multi-session:              disabled        disabled                
   operational:                disabled        disabled                
   add-path:                   disabled        disabled                
   extended-message:            enabled        disabled                
   graceful-restart:           disabled         enabled                

  Families                        Local          Remote        Add-Path
   ipv4 unicast:                enabled         enabled        disabled

  Message Statistic                Sent        Received
   open:                              1               1                
   notification:                      0               0                
   keepalive:                       306             332                
   update:                            3               1                
   refresh:                           0               0                
   total:                           310             334                

Neighbor 2111:ff:XXXX::4

  Session                         Local
   local                2111:ff:XXXX::22                                
   state                    ESTABLISHED                                
   up for                       0:10:10                                

  Setup                           Local          Remote
   AS                             65000           65000                
   ID                    192.168.150.22  192.168.150.22                
   hold-time                          6              90                

  Capability                      Local          Remote
   asn4:                        enabled         enabled                
   route-refresh:              disabled         enabled                
   multi-session:              disabled        disabled                
   operational:                disabled        disabled                
   add-path:                   disabled        disabled                
   extended-message:            enabled        disabled                
   graceful-restart:           disabled         enabled                

  Families                        Local          Remote        Add-Path
   ipv6 unicast:                enabled         enabled        disabled

  Message Statistic                Sent        Received
   open:                              1               1                
   notification:                      0               0                
   keepalive:                       306             332                
   update:                            2               1                
   refresh:                           0               0                
   total:                           309             334                

neighbor 192.168.150.5 {
  description "";
  router-id 192.168.150.22;
  host-name srv2
  domain-name srv2;
  local-address 192.168.150.22;
  local-as 65000;
  peer-as 65000;
  hold-time 6;
  rate-limit disable;
  manual-eor false;

  passive false;
  group-updates true;
  auto-flush true;
  adj-rib-in true;
  adj-rib-out true;
  md5-base64 auto;
  md5-ip "192.168.150.22";

  capability {
    asn4 enable;
    route-refresh disable;
    graceful-restart disable;
    nexthop disable;
    add-path disable;
    multi-session disable;
    operational disable;
    aigp disable;
  }
  family {
    ipv4 unicast;
  }
  nexthop {
  }
  add-path {
  }
  api {
    processes [ service-v4 ];
  }
}
neighbor 2111:ff:XXXX::5 {
  description "";
  router-id 192.168.150.22;
  host-name srv2;
  domain-name srv2;
  local-address 2111:ff:XXXX::22;
  local-as 65000;
  peer-as 65000;
  hold-time 6;
  rate-limit disable;
  manual-eor false;

  passive false;
  group-updates true;
  auto-flush true;
  adj-rib-in true;
  adj-rib-out true;
  md5-base64 auto;
  md5-ip "2111:ff:XXXX::22";

  capability {
    asn4 enable;
    route-refresh disable;
    graceful-restart disable;
    nexthop disable;
    add-path disable;
    multi-session disable;
    operational disable;
    aigp disable;
  }
  family {
    ipv6 unicast;
  }
  nexthop {
  }
  add-path {
  }
  api {
    processes [ service-v6 ];
  }
}
neighbor 192.168.150.4 {
  description "";
  router-id 192.168.150.22;
  host-name srv2;
  domain-name srv2;
  local-address 192.168.150.22;
  local-as 65000;
  peer-as 65000;
  hold-time 6;
  rate-limit disable;
  manual-eor false;

  passive false;
  group-updates true;
  auto-flush true;
  adj-rib-in true;
  adj-rib-out true;
  md5-base64 auto;
  md5-ip "192.168.150.22";

  capability {
    asn4 enable;
    route-refresh disable;
    graceful-restart disable;
    nexthop disable;
    add-path disable;
    multi-session disable;
    operational disable;
    aigp disable;
  }
  family {
    ipv4 unicast;
  }
  nexthop {
  }
  add-path {
  }
  api {
    processes [ service-v4 ];
  }
}
neighbor 2111:ff:XXXX::4 {
  description "";
  router-id 192.168.150.22;
  host-name srv2;
  domain-name srv2;
  local-address 2111:ff:XXXX::22;
  local-as 65000;
  peer-as 65000;
  hold-time 6;
  rate-limit disable;
  manual-eor false;

  passive false;
  group-updates true;
  auto-flush true;
  adj-rib-in true;
  adj-rib-out true;
  md5-base64 auto;
  md5-ip "2111:ff:XXXX::22";

  capability {
    asn4 enable;
    route-refresh disable;
    graceful-restart disable;
    nexthop disable;
    add-path disable;
    multi-session disable;
    operational disable;
    aigp disable;
  }
  family {
    ipv6 unicast;
  }
  nexthop {
  }
  add-path {
  }
  api {
    processes [ service-v6 ];
  }
}
```

```
ExaBGP : 4.2.11
Python : 3.6.8 (default, Aug 24 2020, 17:57:11)  [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

Let me know if you need additional info.

**Comment by thomas-mangin** [comment] 2021-02-09 21:22
All other vendors auto-add IPv6 to the list of AFI/SAFI families negotiated when the peer is an IPv6 neighbor but we do not!

Technically, you may want this behavior, a BGP neighbor that can listen on IPv6 with which you only want to exchange IPv4 routes but in practice, it is not what people expect.

So while it is surprising, it is not a bug per se. Manually adding the family to the configuration is the right thing to do, explicitly stating that you want to send/accept IPv6 prefixes.

Thank you for pointing it.

**Comment by thomas-mangin** [comment] 2021-03-14 18:19
no news is good news. so closing :-)
```
  family {
    ipv4 unicast;
    ipv6 unicast;
  }
```
is what should be setup on IPv6 peers :-)

**Closed by thomas-mangin** 2021-03-14 18:19 UTC
Labels: question
