### ISSUE TITLE
Exabgp not sending all BGP-LU routes

### ISSUE THREAD

**Issue by bhatshrinidhir** [Exa-Networks/exabgp#767] opened 2018-01-07 20:19 UTC
##### ISSUE TYPE
- Feature

##### OS
Linux 3.18.28-7019086.Arora18quickFix.fc18.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

##### VERSION

```
~ @syscon> /usr/bin/exabgp --version
ExaBGP : 4.0.1-4501ddf3
Python : 2.7.13 (default, Dec 15 2017, 23:52:24)  [GCC 4.7.2 20121109 (Red Hat 4.7.2-8)]
Uname  : Linux 3.18.28-7019086.Arora18quickFix.fc18.x86_64 #1 SMP Sun Dec 10 09:57:42 PST 2017 x86_64
Root   : /usr
```

##### ENVIRONMENT 

```
/etc/exabgp @syscon> env exabgp.tcp.bind="0.0.0.0" /usr/bin/exabgp --di

[exabgp.api]
ack = false

[exabgp.tcp]
bind = '[0.0.0.0]'
```

##### SUMMARY
I'm running Exabgp process on a Linux VM and sending 13,500 BGP-LU routes to a Router. 

I see that on the Router random number of routes are received, for example 12,000, sometimes 12.5k and so on. There seems to be no pattern to which routes are not being sent by Exabgp. 

##### STEPS TO REPRODUCE

[exabgp-output.txt](https://github.com/Exa-Networks/exabgp/files/1610255/exabgp-output.txt)

##### EXPECTED RESULTS

I expected all the 1350 bgp-lu routes to be sent to the router.

##### ACTUAL RESULTS

Random number of bgp-lu routes are received on the router.

**Comment by bahtshrinidhi** [comment] 2018-01-08 08:25
@thomas-mangin  could this issue be similar to #736 ?

**Comment by thomas-mangin** [comment] 2018-01-11 22:42
could https://github.com/Exa-Networks/exabgp/commit/359993cfbeed742357be60f3d211e9ed00904dca have been the root cause ?

**Comment by thomas-mangin** [comment] 2018-01-21 09:59
To explain we could run command send via the API out of order, so a sequence withdraw/add could have ended the other way.

**Comment by thomas-mangin** [comment] 2018-04-02 12:58
@bhatshrinidhir ping ? all ok ? can I close the issue please ?

**Comment by bhatshrinidhir** [comment] 2018-04-05 06:42
@thomas-mangin yes the issue can be closed. Thanks for fixing the issue. I did not get a chance to test this again after reporting the issue, but I will do it when I get some time.
Thanks again, for fixing the issue!

**Closed** 2018-04-06 21:44 UTC
Labels: bug, fixed-need-testing
