### ISSUE TITLE
Issue on adj-rib out when doing restart.

### ISSUE THREAD

**Issue by pizu** [Exa-Networks/exabgp#1112] opened 2022-08-03 10:56 UTC
# exabgp --version
ExaBGP : 4.2.4
Python : 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
Uname  : Linux mstdns03 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64
Root   : 

We have 2 BGP's configured, the 2nd bgp we are receiving the routes with no issue but the routes are not being sent, however when doing reload instead of restart we can see the local routes going out for the 2nd BGP.

Thanks.

**Comment by pizu** [comment] 2022-08-03 11:56
if we remove the watchdog the issue disappears. in reality the watchdog works as when doing a service reload of the exabgp it woks too even when we have the watchdog configured.

**Comment by thomas-mangin** [comment] 2022-08-03 16:41
This is a very old version of exabgp and I am not able to test things for the next few days as I am on yearly vacation. Could you please confirm if the issue is still present the latest version

**Comment by thomas-mangin** [comment] 2022-08-22 15:12
With the information provided, I am incapable of understanding what you are doing and can not replicate. I will close the issue but feel free to re-open or open a new one with more information. If I can replicate what you are doing, I will then look into it.

**Closed by thomas-mangin** 2022-08-22 15:12 UTC
Labels: bug
