### ISSUE TITLE
External-BGP not working due to error in AS-PATH serialisation

### ISSUE THREAD

**Issue by brhrenad** [Exa-Networks/exabgp#1066] opened 2022-02-04 12:32 UTC
BGP Peering resets immediatly, because an AttributeError is raised inside /src/bgp/message/update/attribute/aspath.py

**Debug Output:**
```
13:30:02 1940466 reactor       connected to peer-1 with outgoing-1 44.0.10.4-44.0.10.1
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         ********************************************************************************
13:30:02 1940466 reactor         EXABGP MISBEHAVED / HELP US FIX IT
13:30:02 1940466 reactor         ********************************************************************************
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         Sorry, you encountered a problem with ExaBGP, as the problem only affects one
13:30:02 1940466 reactor         peer, we are trying to keep the program running.
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         There are a few things you can do to help us (and yourself):
13:30:02 1940466 reactor         - make sure you are running the latest version of the code available at
13:30:02 1940466 reactor           https://github.com/Exa-Networks/exabgp/releases/latest
13:30:02 1940466 reactor         - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
13:30:02 1940466 reactor           so it can be fixed (github can be searched for similar reports)
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         PLEASE, when reporting, do include as much information as you can:
13:30:02 1940466 reactor         - do not obfuscate any data (feel free to send us a private  email with the
13:30:02 1940466 reactor           extra information if your business policy is strict on information sharing)
13:30:02 1940466 reactor           https://github.com/Exa-Networks/exabgp/wiki/FAQ
13:30:02 1940466 reactor         - if you can reproduce the issue, run ExaBGP with the command line option -d
13:30:02 1940466 reactor           it provides us with much needed information to fix problems quickly
13:30:02 1940466 reactor         - include the information presented below
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         Should you not receive an acknowledgment of your issue on github (assignement,
13:30:02 1940466 reactor         comment, or similar) within a few hours, feel free to email us to make sure
13:30:02 1940466 reactor         it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         ********************************************************************************
13:30:02 1940466 reactor         -- Please provide ALL the information below on :
13:30:02 1940466 reactor         -- https://github.com/Exa-Networks/exabgp/issues
13:30:02 1940466 reactor         ********************************************************************************
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         ExaBGP version : 4.2.6
13:30:02 1940466 reactor         Python version : 3.9.9 (main, Nov 20 2021, 21:30:06)  [GCC 11.1.0]
13:30:02 1940466 reactor         System Uname   : #1 SMP PREEMPT Thu, 25 Nov 2021 22:09:33 +0000
13:30:02 1940466 reactor         System MaxInt  : 9223372036854775807
13:30:02 1940466 reactor         Root           : /dnn/net_setups/konfraum/bgp-router-neu/exabgp
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         Environment:
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         <class 'AttributeError'>
13:30:02 1940466 reactor         'ASN' object has no attribute 'ID'
13:30:02 1940466 reactor         Traceback (most recent call last):
13:30:02 1940466 reactor           File "/dnn/net_setups/konfraum/bgp-router-neu/exabgp/src/exabgp/reactor/peer.py", line 558, in _run
13:30:02 1940466 reactor             for action in self._main():
13:30:02 1940466 reactor           File "/dnn/net_setups/konfraum/bgp-router-neu/exabgp/src/exabgp/reactor/peer.py", line 506, in _main
13:30:02 1940466 reactor             next(new_routes)
13:30:02 1940466 reactor           File "/dnn/net_setups/konfraum/bgp-router-neu/exabgp/src/exabgp/reactor/protocol.py", line 362, in new_update
13:30:02 1940466 reactor             for message in update.messages(self.negotiated, include_withdraw):
13:30:02 1940466 reactor           File "/dnn/net_setups/konfraum/bgp-router-neu/exabgp/src/exabgp/bgp/message/update/__init__.py", line 167, in messages
13:30:02 1940466 reactor             attr = self.attributes.pack(negotiated, include_defaults)
13:30:02 1940466 reactor           File "/dnn/net_setups/konfraum/bgp-router-neu/exabgp/src/exabgp/bgp/message/update/attribute/attributes.py", line 255, in pack
13:30:02 1940466 reactor             message += default[code](local_asn, peer_asn).pack(negotiated)
13:30:02 1940466 reactor           File "/dnn/net_setups/konfraum/bgp-router-neu/exabgp/src/exabgp/bgp/message/update/attribute/aspath.py", line 116, in pack
13:30:02 1940466 reactor             return self._asn_pack(self.aspath, negotiated.asn4)
13:30:02 1940466 reactor           File "/dnn/net_setups/konfraum/bgp-router-neu/exabgp/src/exabgp/bgp/message/update/attribute/aspath.py", line 112, in _asn_pack
13:30:02 1940466 reactor             return self._attribute(self._segments(aspath, asn4))
13:30:02 1940466 reactor           File "/dnn/net_setups/konfraum/bgp-router-neu/exabgp/src/exabgp/bgp/message/update/attribute/aspath.py", line 107, in _segments
13:30:02 1940466 reactor             segments += cls._segment(content.ID, content, asn4)
13:30:02 1940466 reactor         AttributeError: 'ASN' object has no attribute 'ID'
13:30:02 1940466 reactor         
13:30:02 1940466 reactor         ********************************************************************************
13:30:02 1940466 reactor         -- Please provide _ALL_ the information above on :
13:30:02 1940466 reactor         -- https://github.com/Exa-Networks/exabgp/issues
13:30:02 1940466 reactor         ********************************************************************************
13:30:02 1940466 reactor         
13:30:02 1940466 outgoing-1      peer reset, message [] error[]
```

**My Config:**
```
neighbor 44.0.10.1 {
        description "Peer 2 Cisco NCS55A2";
        router-id 44.0.10.4;
        local-address 44.0.10.4;
        local-as 4444;
         peer-as 49808;
 
         family {
                 ipv4 unicast;
         }
 
         announce {
                ipv4 {
                         unicast 44.4.0.0/17 next-hop 44.0.10.4;
                 }
         }
}
```

**For myself I fixed that issue, by changing one line**

```
diff --git a/src/exabgp/bgp/message/update/attribute/aspath.py b/src/exabgp/bgp/message/update/attribute/aspath.py
index 4b61bf0e..c1f2056a 100644
--- a/src/exabgp/bgp/message/update/attribute/aspath.py
+++ b/src/exabgp/bgp/message/update/attribute/aspath.py
@@ -109,7 +109,7 @@ class ASPath(Attribute):
 
     @classmethod
     def _asn_pack(self, aspath, asn4):
-        return self._attribute(self._segments(aspath, asn4))
+        return self._attribute(self._segment(Attribute.CODE.AS_PATH, aspath, asn4))
 
     def pack(self, negotiated):
         if negotiated.asn4:
```

Best Regards,

Bernhard

**Comment by thomas-mangin** [comment] 2022-02-06 16:48
Hi Bernhard,

Thank you for reporting the issue, however, I can not reproduce it (see what I tried below). The patch you are using, while resolving your issue, does not look right to me.

Could you please run `exabgp` with the option `-d` without your patch and provide me with the output (here of privately), as otherwise, I will not be able to understand what is happening.

The reason my test is failing is most likely due to how the session was negotiated and I can not see this without the OPEN messages which are printed when the session is established and the UPDATE message (or command) which is causing the problem.

Test performed:

```
neighbor 127.0.0.1 {
        description "Peer 2 Cisco NCS55A2";
        router-id 44.0.10.4;
        local-address 127.0.0.1;
        local-as 4444;
        peer-as 4444;
 
         family {
                 ipv4 unicast;
         }
 
         announce {
                ipv4 {
                         unicast 44.4.0.0/17 next-hop 44.0.10.4;
                 }
         }
}
```

```sh
#./sbin/exabgp test.conf -d
#sudo ./qa/sbin/bgp --echo
```

**Comment by brhrenad** [comment] 2022-02-06 22:31
Hi Thomas,

It seems that a iBGP session works fine. I guess AS-PATH need not to be altered in this case.
I can confirm that your iBGP example works just fine.

The peering session with my router went flawlessly through the opening States. (Both peers send thier BGP-OPEN Messages.)
In the preparing process of an UPDATE-Message coming from exabgp, exabgp crashes.

If you accept my pull-request, you can exactly recreate my issue. 

**test.conf:**
```
neighbor 127.0.0.1 {
        description "Peer 2 Cisco NCS55A2";
        router-id 44.0.10.4;
        local-address 127.0.0.1;
        local-as 4444;
        peer-as 5555;

         family {
                 ipv4 unicast;
         }

         announce {
                ipv4 {
                         unicast 44.4.0.0/17 next-hop 44.0.10.4;
                 }
         }
}
```

```
#./sbin/exabgp test.conf -d
#sudo ./qa/sbin/bgp --sink --local-as 5555
```

**Comment by thomas-mangin** [comment] 2022-02-08 00:00
Bug introduce at https://github.com/Exa-Networks/exabgp/commit/f941e380fed8a6f73ed41ebba6968d63a9ca3780
and fixed (but referenced #1055 by accident! sigh!)

**Comment by thomas-mangin** [comment] 2022-02-08 00:04
Thank you @brhrenad your patch was correct functionally - so you can keep your patched version 🥳 , I just expressed the fix differently.

**Comment by thomas-mangin** [comment] 2022-02-08 00:58
should work from https://github.com/Exa-Networks/exabgp/commit/f93209a1a3e19959d04f5e3e200f2920c89fc7a3 undoing part of the previous commit and making sure `./qa/bin/parsing` is working

**Comment by frankshoots** [comment] 2022-02-10 04:30
We just installed exabgp today and ran into this same issue. I'm so glad that you were able to fix it just two days ago. We were able to get it working by manually replacing that aspath.py file. Hopefully it gets added to the stable release soon. Thanks to both of you!

**Comment by thomas-mangin** [comment] 2022-02-10 19:44
The stable 4.2.x stable version should not be affected and is really what should be run in production unless you are hitting a bug we can not backport.

The bug was only master AFAICS so just updating (as master has no release) should do the trick 'git pull' in the clone folder. replacing the file should be fine as it rarely changes and therefore all should work as expected (even if it is not recommended).

**Comment by thomas-mangin** [comment] 2022-02-10 19:50
@frankshoots if what I said is not right, please let me know and I will look at 4.2 too but the bug may be different.

**Comment by frankshoots** [comment] 2022-02-11 02:01
Aloha @thomas-mangin, I think we just happened to install exabgp right before you introduced the fix. We are using version 4.2.6. When we tried using the healthcheck script to advertise routes, the BGP session to our router dropped. This also happened when we tried to use the exabgpcli tool to manually advertise routes. After manually copying and replacing the aspath.py file with the updated version from 3 days ago, the issue was resolved. I do see now that when cloning the git repository the aspath.py file contains the fix.

Here is the output of the debug:

`Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         ********************************************************************************
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         EXABGP MISBEHAVED / HELP US FIX IT
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         ********************************************************************************
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         Sorry, you encountered a problem with ExaBGP, as the problem only affects one
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         peer, we are trying to keep the program running.
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         There are a few things you can do to help us (and yourself):
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         - make sure you are running the latest version of the code available at
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           https://github.com/Exa-Networks/exabgp/releases/latest
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           so it can be fixed (github can be searched for similar reports)
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         PLEASE, when reporting, do include as much information as you can:
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         - do not obfuscate any data (feel free to send us a private  email with the
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           extra information if your business policy is strict on information sharing)
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           https://github.com/Exa-Networks/exabgp/wiki/FAQ
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         - if you can reproduce the issue, run ExaBGP with the command line option -d
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           it provides us with much needed information to fix problems quickly
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         - include the information presented below
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         Should you not receive an acknowledgment of your issue on github (assignement,
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         comment, or similar) within a few hours, feel free to email us to make sure
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         ********************************************************************************
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         -- Please provide ALL the information below on :
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         -- https://github.com/Exa-Networks/exabgp/issues
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         ********************************************************************************
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         ExaBGP version : 4.2.6
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         Python version : 3.6.8 (default, Sep  9 2021, 07:49:02)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         System Uname   : #1 SMP Mon Jan 17 07:06:06 EST 2022
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         System MaxInt  : 9223372036854775807
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         Root           : /opt/exabgp
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         Environment:
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         exabgp.daemon.user='root'
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         exabgp.log.level=DEBUG
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         exabgp.log.all=true
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         <class 'AttributeError'>
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         'ASN' object has no attribute 'ID'
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         Traceback (most recent call last):
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           File "/opt/exabgp/src/exabgp/reactor/peer.py", line 558, in _run
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor             for action in self._main():
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           File "/opt/exabgp/src/exabgp/reactor/peer.py", line 506, in _main
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor             next(new_routes)
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           File "/opt/exabgp/src/exabgp/reactor/protocol.py", line 362, in new_update
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor             for message in update.messages(self.negotiated, include_withdraw):
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           File "/opt/exabgp/src/exabgp/bgp/message/update/__init__.py", line 167, in messages
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor             attr = self.attributes.pack(negotiated, include_defaults)
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           File "/opt/exabgp/src/exabgp/bgp/message/update/attribute/attributes.py", line 255, in pack
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor             message += default[code](local_asn, peer_asn).pack(negotiated)
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           File "/opt/exabgp/src/exabgp/bgp/message/update/attribute/aspath.py", line 116, in pack
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor             return self._asn_pack(self.aspath, negotiated.asn4)
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           File "/opt/exabgp/src/exabgp/bgp/message/update/attribute/aspath.py", line 112, in _asn_pack
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor             return self._attribute(self._segments(aspath, asn4))
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor           File "/opt/exabgp/src/exabgp/bgp/message/update/attribute/aspath.py", line 107, in _segments
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor             segments += cls._segment(content.ID, content, asn4)
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         AttributeError: 'ASN' object has no attribute 'ID'
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         ********************************************************************************
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         -- Please provide _ALL_ the information above on :
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         -- https://github.com/Exa-Networks/exabgp/issues
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         ********************************************************************************
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: outgoing-24     peer reset, message [] error[]`

**Comment by thomas-mangin** [comment] 2022-02-11 10:01
```
commit 640b05aabdb14707f945415d4f1405993401446f (tag: 4.2.6)
Author: Thomas Mangin <thomas.mangin@exa.net.uk>
Date:   Wed Feb 5 17:11:17 2020 +0000

    updating version to 4.2.6
```


4.2.6 is ancient, probably came with your OS package, but this is not what you are running:

```
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor             segments += cls._segment(content.ID, content, asn4)
Feb  9 17:47:07 lab-dnsdist-03 exabgp[14129]: reactor         AttributeError: 'ASN' object has no attribute 'ID'
```

The string `content.ID` can not be found in the source of 4.2.6 or 4.2.17 therefore you must have been running master before the fix. 

```
❯ git co 4.2.6
[...]
❯ grep -r "content.ID" lib 

❯ git co 4.2              
Previous HEAD position was 640b05aa updating version to 4.2.6
Switched to branch '4.2'
Your branch is up to date with 'origin/4.2'.

❯ grep -r "content.ID" lib

```

**Comment by thomas-mangin** [comment] 2022-03-24 09:41
Can I take the lack of update as a good sign?

**Comment by frankshoots** [comment] 2022-03-24 21:53
> 

We ended writing custom scripts to do our monitoring and route withdrawals, so exabgp was removed from the server. I like the solution though. I'm going to keep it in mind for future projects. Thanks for the assistance!

**Comment by thomas-mangin** [comment] 2022-03-25 09:17
No worries.

**Closed by thomas-mangin** 2022-03-25 09:17 UTC
Labels: bug, fixed-need-testing

**Comment by brhrenad** [comment] 2022-03-25 12:12
Hi Thomas,

Sorry for the lack of updates.
At the time I had a active lab setup running, so I wasn't able to test your changes immediatly.

But I tested the fix with a couple of Cisco IOS XR devices and it seems that it works fine.

I tested it additionally with explicitly defined AS-Path. (The change I made myself actually broke this)
```
        announce {
                ipv4 {
                        unicast 44.4.250.0/24 next-hop 44.0.10.7 as-path [4230, 4250, 4250];
                }
        }
```

I wasn't able to test peering with none asn4 capable Routers. Tue do lacking ancient BGP-Speakers in our lab.
Nonetheless, I agree with you by closing this issue.

Thank you very much! 👍 

BR Bernhard
