### ISSUE TITLE
exabgp configuration testing fails due to 'strings are different' on IGP configuration

### ISSUE THREAD

**Issue by MEschenbacher** [Exa-Networks/exabgp#732] opened 2017-10-11 10:07 UTC
##### ISSUE TYPE
 - Bug Report

##### OS
Debian

##### VERSION

Tested with version 3, 4 and git master:
```
ExaBGP : 3.4.17
Python : 2.7.13+ (default, Jul 19 2017, 18:15:03)  [GCC 6.4.0 20170704]
Uname  : #1 SMP Debian 4.11.11-1 (2017-07-17)
```
```                                         
ExaBGP : 4.0.2-1c737d99
Python : 3.5.4 (default, Aug 12 2017, 14:08:14)  [GCC 7.1.0]
Uname  : Linux work-vm 4.11.0-2-amd64 #1 SMP Debian 4.11.11-1 (2017-07-17) x86_64
Root   : /home/max/git/wi2/virtualenv
```
```
ExaBGP : master-0192312a3dbc40c80d21922e9862ca7163fd2f27
Python : 3.5.4 (default, Aug 12 2017, 14:08:14)  [GCC 7.1.0]
Uname  : Linux work-vm 4.11.0-2-amd64 #1 SMP Debian 4.11.11-1 (2017-07-17) x86_64
Root   : /home/max/git/exabgp
```

##### ENVIRONMENT 

Version 3.4
```
[exabgp.daemon]
user = 'exabgp'
```
Versions 4 and git master
```
[exabgp.api]
encoder = text
respawn = false

[exabgp.daemon]
user = 'exabgp'
```

##### CONFIGURATION
```
neighbor 10.0.0.2 {
	description "dummy";
	router-id 10.0.0.1;
	local-address 10.0.0.1;
	peer-as 65000;
	local-as 64699;

	flow {
		route rule-5 {
			match {
				destination 10.4.42.0/24;
			}
			then {
				rate-limit 2500000;
			}
		}
	}
}

```

##### SUMMARY
Configuration testing fails `exabgp -t exabgp.conf` due to
> INFO     | 15377  | parser        | strings are different:
> INFO     | 15377  | parser        | [flow destination 10.4.42.0/24 extended-community rate-limit 2500000]
> INFO     | 15377  | parser        | [flow destination 10.4.42.0/24 as-path [ 64699 ] extended-community rate-limit 2500000]

##### STEPS TO REPRODUCE
run `exabgp -t exabgp.conf` on the provided configuration

##### EXPECTED RESULTS
Configuration testing should succeed as the configuration itself is accepted when running exabgp.

##### ACTUAL RESULTS
Apparently igp routes cause the internal testing to fail.

##### IMPORTANCE
Not production.

**Comment by MEschenbacher** [comment] 2017-10-11 21:24
`exabgp -t` also fails on a non-private asn + public asn combination (same issue). I assume this happens as soon as `local-as != peer-as`.

**Comment by thomas-mangin** [comment] 2017-10-16 13:04
Hello Maximilian,

Yes, indeed the difference is due to the fact that the session is configured with EBGP. This means that the message to be sent NEEDS the prepending of the local ASN and therefore the message configured and sent will be different.

The option `-t` was created for our internal testing which is iBGP only in purpose 😜  - I never expected people to use it .. but as it is documented, I will make sure to fix this issue.

**Comment by MEschenbacher** [comment] 2017-11-08 12:45
Thanks for addressing this issue.

For branch 3.4, this still fails, even with commit 0edcf44f:
```$ ./sbin/exabgp -v
ExaBGP : 3.4.22
Python : 2.7.13 (default, Jan 19 2017, 14:48:08)  [GCC 6.3.0 20170118]
Uname  : #1 SMP Debian 4.12.13-1 (2017-09-19)

$ ./sbin/exabgp -t exabgp.conf
Wed, 08 Nov 2017 13:38:55 | INFO     | 9275   | configuration | environment file missing
Wed, 08 Nov 2017 13:38:55 | INFO     | 9275   | configuration | generate it using "exabgp --fi > /home/max/git/exabgp/etc/exabgp/exabgp.env"
Wed, 08 Nov 2017 13:38:55 | INFO     | 9275   | reactor       | Performing reload of exabgp 3.4.22
[...snip...]
Wed, 08 Nov 2017 13:42:50 | INFO     | 10441  | parser        | recoded route flow destination 10.4.42.0/24 origin igp as-path [ 64699 ] extended-community rate-limit 2500000
Wed, 08 Nov 2017 13:42:50 | INFO     | 10441  | parser        | recoded hex   FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 003D 0200 0000 2640 0101 0040 0206 0201 0000 FCBB C010 0880 0600 004A 1896 8080 0E0B 0001 8500 0005 0118 0A04 2A
Wed, 08 Nov 2017 13:42:50 | INFO     | 10441  | parser        | strings are different:
Wed, 08 Nov 2017 13:42:50 | INFO     | 10441  | parser        | [flow destination 10.4.42.0/24 next-hop none extended-community rate-limit 2500000]
Wed, 08 Nov 2017 13:42:50 | INFO     | 10441  | parser        | [flow destination 10.4.42.0/24 as-path [ 64699 ] extended-community rate-limit 2500000]
```

For branch master, `exabgp -t` still fails but due to a different error:

```$ exabgp -v
ExaBGP : master-b367255d7e184d1d87153cd6bae1158cbf31d99c
Python : 3.5.4 (default, Aug 12 2017, 14:08:14)  [GCC 7.1.0]
Uname  : Linux schu 4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64
Root   : /home/max/git/exabgp

$ ./sbin/exabgp -t exabgp.conf
13:34:09 | 7415   | welcome       | Thank you for using ExaBGP
13:34:09 | 7415   | version       | master-b367255d7e184d1d87153cd6bae1158cbf31d99c
13:34:09 | 7415   | interpreter   | 3.5.4 (default, Aug 12 2017, 14:08:14)  [GCC 7.1.0]
13:34:09 | 7415   | os            | Linux schu 4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64
13:34:09 | 7415   | installation  | /home/max/git/exabgp
13:34:09 | 7415   | advice        | environment file missing
13:34:09 | 7415   | advice        | generate it using "exabgp --fi > /home/max/git/exabgp/etc/exabgp/exabgp.env"
13:34:09 | 7415   | cli           | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
13:34:09 | 7415   | cli           | we scanned the following folders (the number is your PID):
13:34:09 | 7415   | cli control   |  - /run/exabgp/
13:34:09 | 7415   | cli control   |  - /run/1000/
13:34:09 | 7415   | cli control   |  - /run/
13:34:09 | 7415   | cli control   |  - /var/run/exabgp/
13:34:09 | 7415   | cli control   |  - /var/run/1000/
13:34:09 | 7415   | cli control   |  - /var/run/
13:34:09 | 7415   | cli control   |  - /home/max/git/exabgp/run/exabgp/
13:34:09 | 7415   | cli control   |  - /home/max/git/exabgp/run/1000/
13:34:09 | 7415   | cli control   |  - /home/max/git/exabgp/run/
13:34:09 | 7415   | cli control   |  - /home/max/git/exabgp/var/run/exabgp/
13:34:09 | 7415   | cli control   |  - /home/max/git/exabgp/var/run/1000/
13:34:09 | 7415   | cli control   |  - /home/max/git/exabgp/var/run/
13:34:09 | 7415   | cli control   | please make them in one of the folder with the following commands:
13:34:09 | 7415   | cli control   | > mkfifo /home/max/git/exabgp/run/exabgp.{in,out}
13:34:09 | 7415   | cli control   | > chmod 600 /home/max/git/exabgp/run/exabgp.{in,out}
13:34:09 | 7415   | cli control   | > chown 1000:1000 /home/max/git/exabgp/run/exabgp.{in,out}
13:34:09 | 7415   | configuration | performing reload of exabgp master-b367255d7e184d1d87153cd6bae1158cbf31d99c
13:34:09 | 7415   | parser        |         
13:34:09 | 7415   | parser        | decoding routes in configuration
13:34:09 | 7415   | configuration | problem with the configuration file, no change done
13:34:09 | 7415   | configuration | problem parsing configuration file line 0
13:34:09 | 7415   | configuration | error message: can't concat str to bytes
```

**Comment by thomas-mangin** [comment] 2017-11-08 13:11
This is a different issue .. can you please run the program with "--d" and enabling the option `exabgp.debug.configuration`.

**Comment by thomas-mangin** [comment] 2017-11-23 20:38
No feedback - closing - please re-open if the issue is still present.

**Closed by thomas-mangin** 2017-11-23 20:38 UTC
Labels: bug, fixed-need-testing
