### ISSUE TITLE
failing to establish peering session between exabgp and ios

### ISSUE THREAD

**Issue by isseykun** [Exa-Networks/exabgp#914] opened 2019-08-30 15:33 UTC
##### Summary

Failing to establish a BGP neighbor relationship with iosxr. The BGP state is stuck in Active. No firewall is configured on Linux and ports are open. Both devices have reachability with the configured address.  
##### OS

```
Ubuntu 18.04.3 LTS
```

```
Linux ipe-erco 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

##### Version

```
ExaBGP : master-25ce4ff57982bcf69902c5919a7d159b5f1befe1
Python : 3.6.8 (default, Jan 14 2019, 11:02:34)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Uname  : Linux ipe-erco 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64
Root   : /opt/exabgp
```

##### Installation

```
git clone https://github.com/Exa-Networks/exabgp.git /opt/exabgp
```

##### Environment 

```
[exabgp.daemon]
daemonize = true
pid = '/opt/exabgp/exabgp.pid'
user = 'www-data'

[exabgp.log]
destination = '/opt/exabgp/exabgp.log'
message = true
packets = true
rib = true
routes = true

[exabgp.pdb]
enable = true

[exabgp.tcp]
bind = '192.168.1.2'
```

##### Configuration

```
neighbor 192.168.1.1 {
    router-id 192.168.1.2;
    local-address 192.168.1.2;
    local-as 65550;
    peer-as 65550;

}
```

##### Program output

```
This is the output from logfile

13790  reactor       initialising connection to peer-1
13790  outgoing-8    attempting connection to 192.168.1.1:179
13790  network       attempting to establish connection
13790  outgoing-8    sending TCP payload ( 177) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 00B1 0104 1DDA 00B4 0A80 F073 9402 0601 0400 0100 0102 0601 0400 0100 0202 0601 0400 0100 0402 0601 0400 0100 8002 0601 0400 0100 8402 0601 0400 0100 8502 0601 0400 0100 8602 0601 0400 0200 0102 0601 0400 0200 0202 0601 0400 0200 0402 0601 0400 0200 8002 0601 0400 0200 8502 0601 0400 0200 8602 0601 0400 1900 4102 0601 0400 1900 4602 0601 0440 0400 4702 0601 0440 0400 4802 0641 0400 001D DA02 0206 00
13790  outgoing-8    outgoing-8 192.168.1.2-192.168.1.1, closing connection
13790  outgoing-8    peer reset, message [closing connection] error[Broken TCP connection]
13790  outgoing-8    outgoing-8 192.168.1.2-192.168.1.1, closing connection
13790  reactor       initialising connection to peer-1
13790  outgoing-9    attempting connection to 192.168.1.1:179
13790  network       attempting to establish connection
13790  reactor       SIGTERM received
13790  reactor       scheduling shutdown
13790  process       issue with the process, restarting it
13790  process       terminating process ercos
13790  process       forked process ercos
13790  reactor       performing shutdown
13790  network       stopped listening on 192.168.1.2:179
13790  outgoing-9    outgoing-9 192.168.1.2-192.168.1.1, closing connection
13790  outgoing-9    connection to 192.168.1.1 closed
13790  process       terminating process api-internal-cli-7f133128
13790  process       terminating process ercos
13790  daemon        Removed PIDfile /opt/exabgp/exabgp.pid
22645  daemon        Created PIDfile /opt/exabgp/exabgp.pid with value 22645
22645  reactor       initialising connection to peer-1
22645  outgoing-1    attempting connection to 192.168.1.1:179
22645  process       command from process ercos : Server available at http://127.0.0.1:3005 
22645  process       responding to ercos : error
22645  api           command from process not understood : Server available at http://127.0.0.1:3005
22645  network       attempting to establish connection
22645  outgoing-1    sending TCP payload ( 177) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 00B1 0104 1DDA 00B4 0A80 F073 9402 0601 0400 0100 0102 0601 0400 0100 0202 0601 0400 0100 0402 0601 0400 0100 8002 0601 0400 0100 8402 0601 0400 0100 8502 0601 0400 0100 8602 0601 0400 0200 0102 0601 0400 0200 0202 0601 0400 0200 0402 0601 0400 0200 8002 0601 0400 0200 8502 0601 0400 0200 8602 0601 0400 1900 4102 0601 0400 1900 4602 0601 0440 0400 4702 0601 0440 0400 4802 0641 0400 001D DA02 0206 00
22645  outgoing-1    outgoing-1 192.168.1.2-192.168.1.1, closing connection
22645  outgoing-1    peer reset, message [closing connection] error[Broken TCP connection]
22645  outgoing-1    outgoing-1 192.168.1.2-192.168.1.1, closing connection
22645  reactor       initialising connection to peer-1
22645  outgoing-2    attempting connection to 192.168.1.1:179
22645  network       attempting to establish connection

systecmctl status exabgp:

exabgp[1233]: 15:47:32 | 1233   | configuration   | > neighbor         | '192.168.1.1'
exabgp[1233]: 15:47:32 | 1233   | configuration   | . router-id        | '192.168.1.2'
exabgp[1233]: 15:47:32 | 1233   | configuration   | . local-address    | '192.168.1.2'
exabgp[1233]: 15:47:32 | 1233   | configuration   | . local-as         | '65550'
exabgp[1233]: 15:47:32 | 1233   | configuration   | . peer-as          | '65550'
exabgp[1233]: 15:47:32 | 1233   | configuration   | < neighbor         |
exabgp[1233]: 15:47:32 | 1233   | reactor         | new peer: neighbor 192.168.1.1 local-ip 192.168.1.2 local-as 65550 peer-as 65550 router-id 192.168.1.2 family-allowed in-open
exabgp[1233]: 15:47:32 | 1233   | network         | listening for BGP session(s) on 192.168.1.2:179
exabgp[1233]: 15:47:32 | 1233   | reactor         | loaded new configuration successfully
exabgp[1233]: 15:47:32 | 1233   | process         | forked process api-internal-cli-7af2e446
```

##### Steps to reproduce

```

```

##### Importance

```
This is in a production environment. The only issue so far is failing to form neighbor relationship
```

**Comment by thomas-mangin** [comment] 2019-08-30 15:37
Hello, This is an ERCO problem https://erco.xyz not ExaBGP - I do not use ERCO I can not help sorry ! It looks like the ERCO web interface is not running.

**Comment by thomas-mangin** [comment] 2019-08-30 15:39
Also it is likely that ERCO was created for ExaBGP 3.4 and not 4.0 and that you will need to disable command acknowledgment for the API
https://github.com/Exa-Networks/exabgp/wiki/Migration-from-3.4-to-4.0

**Comment by isseykun** [comment] 2019-08-30 15:40
the problem is not with the erco, I have tested using only the neighbor set from the above config and it fails to form adj

**Comment by thomas-mangin** [comment] 2019-08-30 20:01
You are right , it is not only the connection to ERCO which is not working. Sending an open message to the peer failed too (first). As a TCP connection could not be esablished, please keep in mind that ExaBGP does not setup your host networking .. so it is not a bug but looks like a setup/configuration issue.

**Comment by thomas-mangin** [comment] 2019-08-31 08:44
Hi @isseykun 

Now having a little bit more time to think about it. 

The ERCO problem could be caused by the SIGTERM (ie, the error in the log is due to an initiated shutdown). The OPEN message was sent (so the TCP session must have established). The connection closed thereafter, so it looks like the other peer accept the TCP session but closed the connection without a NOTIFICATION.

I am confused as RFC 4271 states:

>    All errors detected while processing the OPEN message MUST be
>    indicated by sending the NOTIFICATION message with the Error Code
>    OPEN Message Error.

As we do not see any NOTIFICATION (information about an error) back from the peer. Could it be that the router is setup to accept connection from multiple IPs within a range and that this IP is not setup ? (or anything which could explain the acceptance of the TCP connection but then closing it on receiving the OPEN message).

What is IOS saying ?

**Comment by isseykun** [comment] 2019-08-31 11:05
@thomas-mangin after further investigation, it was the issue of the switching interface. By changing to a new port, its working perfectly. Hence you may delete this case as it's not relevant to exabgp. Appreciate your valuable time for this.

**Comment by thomas-mangin** [comment] 2019-09-02 06:29
Happy you could find the root of the issue ...

**Closed by thomas-mangin** 2019-09-02 06:29 UTC
Labels: question
