### ISSUE TITLE
Connection still up after 'state -> down' notification

### ISSUE THREAD

**Issue by spakka** [Exa-Networks/exabgp#508] opened 2016-10-04 14:00 UTC
Hi Thomas,

We found a peer which triggered the following log message:
```
Oct  3 08:57:51 rrc19 exabgp: 4673   reactor       New peer setup: neighbor 196.46.25.216 local-ip 196.46.25.86 local-as 12654 peer-as 2018 router-id 196.46.25.86 family-allowed in-open
Oct  3 08:57:51 rrc19 exabgp: 4673   reactor       New peer setup: neighbor 2001:43f8:6d0::216 local-ip 2001:43f8:6d0::86 local-as 12654 peer-as 2018 router-id 196.46.25.86 family-allowed in-open
Oct  3 08:57:54 rrc19 exabgp: 4673   network       Connected to peer neighbor 196.46.25.216 local-ip 196.46.25.86 local-as 12654 peer-as 2018 router-id 196.46.25.86 family-allowed in-open (out)
Oct  3 08:57:54 rrc19 exabgp: 4673   network       Connected to peer neighbor 2001:43f8:6d0::216 local-ip 2001:43f8:6d0::86 local-as 12654 peer-as 2018 router-id 196.46.25.86 family-allowed in-open (out)
Oct  4 00:48:47 rrc19 exabgp: 4673   network       Peer   196.46.25.216 ASN 2018    automatic protocol cleanup
Oct  4 00:48:47 rrc19 exabgp: 4673   network       Peer 2001:43f8:6d0::216 ASN 2018    automatic protocol cleanup
```
whatever this event at Oct  4 00:48:47 was, it sent the following to client process:
```
{
  "neighbor": {
    "reason": "automatic protocol cleanup",
    "state": "down",
    "asn": {
      "peer": "2018",
      "local": "12654"
    },
    "address": {
      "peer": "196.46.25.216",
      "local": "196.46.25.86"
    },
    "ip": "196.46.25.216"
  },
  "type": "state",
  "counter": 3837054,
  "ppid": "1",
  "pid": "4673",
  "host": "rrc19.ripe.net",
  "time": 1475542127.33,
  "exabgp": "3.4.8"
}

{
  "neighbor": {
    "reason": "automatic protocol cleanup",
    "state": "down",
    "asn": {
      "peer": "2018",
      "local": "12654"
    },
    "address": {
      "peer": "2001:43f8:6d0::216",
      "local": "2001:43f8:6d0::86"
    },
    "ip": "2001:43f8:6d0::216"
  },
  "type": "state",
  "counter": 8379281,
  "ppid": "1",
  "pid": "4673",
  "host": "rrc19.ripe.net",
  "time": 1475542127.33,
  "exabgp": "3.4.8"
}
```
But the connection stayed up, and we continue to receive update messages from the peer, these are still being passed onto the client process.

This confused our RIB state processing engine as the last 'state' change for the peer was 'down'.

Do you have any idea how this might have happened? It looks like this originates from Protocol.close, but that looks like it should kill the connection, so we don't understand how the connection is still up :)
(v.3.4.15)

Thanks!
Colin

**Comment by thomas-mangin** [comment] 2016-10-04 14:12
in protocol.py
```
	def __del__ (self):
		self.close('automatic protocol cleanup')
```
I assume an incoming connection was made by the peer. The connection was found to already exist and then was deleted. This code does not check if close() was already explicitly called on the object, and it should be
```
		self.close('automatic protocol cleanup',False)
```
if this is just a delete .. going to write a patch you can then test.

**Comment by spakka** [comment] 2016-10-04 14:16
We aren't listening on port 179. Not sure how it could detect an incoming connection from the peer, even if the peer tried.

**Comment by thomas-mangin** [comment] 2016-10-04 14:36
ok - thanks for that information - I was looking into it - it will save me time debugging.

**Comment by thomas-mangin** [comment] 2016-10-04 14:44
The 'ugly' fix would be the change the function to use `,False` but it does not explain how the protocol can continue to work once the connection has closed !
I am very puzzled.

**Comment by thomas-mangin** [comment] 2016-10-04 14:57
The class doing the reading is `Outgoing` which is a subclass of `Connection`.

In this class we assign `self.io`, I am wondering if the fact that defined `__del__` in the parent but not the child means that when we call it, it does not consider both value the same (which would explain the behaviour, but is not something I believe should be).

This code was only there to 'catch' if we forgot to close the object explicitly and AFAICS we never do (as we use exception to grab errors and do it). 

So we can either add `,False` and keep it, or remove it. While this is not ideal (as it does not find the root cause of the issue), it will fix the issue.

Any better suggestion ?

**Comment by spakka** [comment] 2016-10-04 15:52
I don't have a better suggestion.
But then I don't totally understand how it could get itself into this state.
We can certainly try it anyway, but then it might be a year or five before the condition would ever come up again, whatever it was :)

**Comment by thomas-mangin** [comment] 2016-10-04 17:07
@spakka having written the code and understanding it well, I really believe it may be a bug/side effect of the python garbage collector.

After a review, we should never need to do this on close, as we always explicitely called close before removing all references to the object.

So I will simply remove the code later on and close this issue, the `__del__` function can just go.

We found some weird issue like this in the past (where the caching of object was broken but the dev would not fix the issue as it would affect deployed application which - while really annoying when the code does not work as should - is good as it does not break real world deployments).

https://mail.python.org/pipermail/new-bugs-announce/2008-July/002344.html
for the details 😜

**Comment by spakka** [comment] 2016-10-04 17:23
OK, thanks for the explanation, thanks for taking the time to look.
I guess I'll need to handle it on our side, in a 'should not get here' condition ;-)

**Closed** 2016-10-06 08:16 UTC
Labels: bug
