### ISSUE TITLE
Open messages with unassigned / reserved capabilities bork json output

### ISSUE THREAD

**Issue by sanjmonkey** [Exa-Networks/exabgp#277] opened 2015-05-27 11:03 UTC
Hello!

I have a peer who looks to be trying to negotiate a legacy (aka vendor specific) implementation of ORF by sending me capability 0x82 in his open message, only, this doesn't look to be being caught into either reserved or unassigned ranges defined in capability.py, and hence borks when trying to assemble the JSON.

removed logs to protect the innocent

**Comment by thomas-mangin** [comment] 2015-05-27 13:16
Ok - looking into this now.

**Comment by thomas-mangin** [comment] 2015-05-27 14:05
ARGH, you are running master. Could you please update and tell me if the issue is still there ?
It may have been as it had a experimental support for the hostname draft.

I have the following performing my test:

Wed, 27 May 2015 15:02:39 | INFO     | 60531  | message       | Peer       127.0.0.1 ASN 65332   << OPEN version=4 asn=65332 hold_time=10800 router_id=38.229.66.20 capabilities=[Multiprotocol(ipv4 unicast), Route Refresh, ASN4(65332), Route Refresh, Reserved 130, Multisession (RFC) ]

Whoa ! The hold time Cogent is sending to sidekick is _LARGE_.

**Comment by thomas-mangin** [comment] 2015-05-27 14:20
fixed with https://github.com/Exa-Networks/exabgp/commit/237be22ae8a74e8e794a613bb76ae0837b3839dd

**Closed by thomas-mangin** 2015-05-27 14:20 UTC
Labels: bug
