### ISSUE TITLE
labeled route with the same label not sent after withdrawal previously

### ISSUE THREAD

**Issue by choisuibun** [Exa-Networks/exabgp#365] opened 2016-01-07 08:25 UTC
Hi,

I have the same route 1.1.1.1/32 sent to neighbor 172.24.66.225 a number of time with different label. After sending and withdrawing couple time, i found that exabgp is not sending out update when i tried to reuse the label same as the one in the route which has been withdraw before. 

Do you know what i can do?

Thanks
Eric

```
100   207    0    41  100   166     20     82  0:00:02  0:00:02 --:--:--    82
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   333    0   104  100   229     34     76  0:00:03  0:00:03 --:--:--    76127.0.0.1 - - [07/Jan/2016 16:11:20] "POST / HTTP/1.1" 200 -
Thu, 07 Jan 2016 16:11:20 | INFO     | 13255  | processes     | Command from process send-routes : neighbor 172.24.66.224 announce route 2.2.2.2/32 label 368928 next-hop 172.24.66.225
Thu, 07 Jan 2016 16:11:20 | INFO     | 13255  | reactor       | Route added to neighbor 172.24.66.224 local-ip 172.24.69.205 local-as 600 peer-as 600 router-id 172.24.69.205 family-allowed in-open : 2.2.2.2/32 label [ 368928 ] next-hop 172.24.66.225
100   333    0   104  100   229     34     75  0:00:03  0:00:03 --:--:--    75
Thu, 07 Jan 2016 16:11:21 | INFO     | 13255  | reactor       | Performing dynamic route update
Thu, 07 Jan 2016 16:11:21 | INFO     | 13255  | reactor       | Updated peers dynamic routes successfully
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   333    0   104  100   229     51    114  0:00:02  0:00:02 --:--:--   114127.0.0.1 - - [07/Jan/2016 16:11:33] "POST / HTTP/1.1" 200 -
Thu, 07 Jan 2016 16:11:33 | INFO     | 13255  | processes     | Command from process send-routes : neighbor 172.24.66.225 announce route 1.1.1.1/32 label 368929 next-hop 172.24.66.224
Thu, 07 Jan 2016 16:11:33 | INFO     | 13255  | reactor       | Route added to neighbor 172.24.66.225 local-ip 172.24.69.205 local-as 600 peer-as 600 router-id 172.24.69.205 family-allowed in-open : 1.1.1.1/32 label [ 368929 ] next-hop 172.24.66.224
100   333    0   104  100   229     51    112  0:00:02  0:00:02 --:--:--   112
Thu, 07 Jan 2016 16:11:33 | INFO     | 13255  | reactor       | Performing dynamic route update
Thu, 07 Jan 2016 16:11:33 | INFO     | 13255  | reactor       | Updated peers dynamic routes successfully
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   333    0   104  100   229     51    114  0:00:02  0:00:02 --:--:--   114127.0.0.1 - - [07/Jan/2016 16:11:46] "POST / HTTP/1.1" 200 -
Thu, 07 Jan 2016 16:11:46 | INFO     | 13255  | processes     | Command from process send-routes : neighbor 172.24.66.225 withdraw route 1.1.1.1/32 label 0 next-hop 172.24.66.224
Thu, 07 Jan 2016 16:11:46 | INFO     | 13255  | reactor       | Route removed : 1.1.1.1/32 label [ 0 ] next-hop 172.24.66.224
100   333    0   104  100   229     51    113  0:00:02  0:00:02 --:--:--   113
Thu, 07 Jan 2016 16:11:47 | INFO     | 13255  | reactor       | Performing dynamic route update
Thu, 07 Jan 2016 16:11:47 | INFO     | 13255  | reactor       | Updated peers dynamic routes successfully
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   333    0   104  100   229     51    114  0:00:02  0:00:02 --:--:--   114127.0.0.1 - - [07/Jan/2016 16:13:07] "POST / HTTP/1.1" 200 -
Thu, 07 Jan 2016 16:13:07 | INFO     | 13255  | processes     | Command from process send-routes : neighbor 172.24.66.225 announce route 1.1.1.1/32 label 368930 next-hop 172.24.66.224
Thu, 07 Jan 2016 16:13:07 | INFO     | 13255  | reactor       | Route added to neighbor 172.24.66.225 local-ip 172.24.69.205 local-as 600 peer-as 600 router-id 172.24.69.205 family-allowed in-open : 1.1.1.1/32 label [ 368930 ] next-hop 172.24.66.224
100   333    0   104  100   229     51    113  0:00:02  0:00:02 --:--:--   113
Thu, 07 Jan 2016 16:13:08 | INFO     | 13255  | reactor       | Performing dynamic route update
Thu, 07 Jan 2016 16:13:08 | INFO     | 13255  | reactor       | Updated peers dynamic routes successfully
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   333    0   104  100   229     25     57  0:00:04  0:00:04 --:--:--    57127.0.0.1 - - [07/Jan/2016 16:13:16] "POST / HTTP/1.1" 200 -
Thu, 07 Jan 2016 16:13:16 | INFO     | 13255  | processes     | Command from process send-routes : neighbor 172.24.66.225 withdraw route 1.1.1.1/32 label 0 next-hop 172.24.66.224
Thu, 07 Jan 2016 16:13:16 | INFO     | 13255  | reactor       | Route removed : 1.1.1.1/32 label [ 0 ] next-hop 172.24.66.224
100   333    0   104  100   229     25     56  0:00:04  0:00:04 --:--:--    56
Thu, 07 Jan 2016 16:13:16 | INFO     | 13255  | reactor       | Performing dynamic route update
Thu, 07 Jan 2016 16:13:16 | INFO     | 13255  | reactor       | Updated peers dynamic routes successfully
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   333    0   104  100   229     51    114  0:00:02  0:00:02 --:--:--   114127.0.0.1 - - [07/Jan/2016 16:13:18] "POST / HTTP/1.1" 200 -
Thu, 07 Jan 2016 16:13:18 | INFO     | 13255  | processes     | Command from process send-routes : neighbor 172.24.66.225 announce route 1.1.1.1/32 label 368929 next-hop 172.24.66.224
Thu, 07 Jan 2016 16:13:18 | INFO     | 13255  | reactor       | Route added to neighbor 172.24.66.225 local-ip 172.24.69.205 local-as 600 peer-as 600 router-id 172.24.69.205 family-allowed in-open : 1.1.1.1/32 label [ 368929 ] next-hop 172.24.66.224
100   333    0   104  100   229     51    113  0:00:02  0:00:02 --:--:--   113
Thu, 07 Jan 2016 16:13:19 | INFO     | 13255  | reactor       | Performing dynamic route update
Thu, 07 Jan 2016 16:13:19 | INFO     | 13255  | reactor       | Updated peers dynamic routes successfully
```

```
group test {
        process receive-routes {
                run ./receive.py;
                encoder json;
                receive {
                        parsed;
                        update;
                        neighbor-changes;
                }
                send {
                        packets;
                }
        }
        process send-routes {
                run ./send.py;
        }

    neighbor 172.24.66.224 {
        router-id 172.24.69.205;
        local-address 172.24.69.205;
        local-as 600;
        peer-as 600;
        process {
                receive {
                        parsed;
                        update;
                        neighbor-changes;
                }
        }
    }

    neighbor 172.24.66.225 {
        router-id 172.24.69.205;
        local-address 172.24.69.205;
        local-as 600;
        peer-as 600;
        process {
                receive {
                        parsed;
                        update;
                        neighbor-changes;
                }
        }
    }
}
```

**Comment by thomas-mangin** [comment] 2016-01-07 11:57
Could it be that you are announcing and withdrawing very fast and that ExaBGP does not use the label when comparing two routes and therefore think the currently already sent prefix is good and does not need updating ?

I can not check right now, but simply putting a delay between the removal and re-announcement (or just announcing the two routes one after the other and seeing if the new route in announced) should allow to check if this is indeed the issue.

**Comment by choisuibun** [comment] 2016-01-07 14:17
hi thomas,

thanks for the quick reply. i tried to withdraw with the exact label that
the route is advertised. it seems to work correctly after that. by default,
junos withdraw the label route with label 0.

perhaps the route was not properly removed with label = 0 in the withdraw
message.

Regards,
Eric

**Comment by thomas-mangin** [comment] 2016-01-07 15:17
Eric, I think you are right. Good that we found a solution to your issue. If happy feel free to close the ticket.

**Comment by tmmorin** [comment] 2016-01-07 17:11
The specs say that the label should be set to zero on a withdraw. This would be nice to fix.

It is very much possible that the comparison functions do not do the right thing yet in exabgp.
In bagpipe, we implemented the correct behavior (withdraw will withdraw all matching routes independent of the label), but I hadn't tried to identify what should be the right behavior for exabgp.

**Comment by thomas-mangin** [comment] 2016-01-08 15:49
@tmmorin I am pretty sure that it is not what the code does - and I will check and fix asap.

**Comment by thomas-mangin** [comment] 2016-02-15 16:54
@tmmorin is the bug still here ?

**Comment by thomas-mangin** [comment] 2016-02-16 19:58
After looking at the code the issue is that the content of the NLRI is used to index a tree which is then checked when removing the route. If the label is set to zero during the inserting on the tree, then generating a route with label zero will correctly remove the route when the withdrawal is generated, but it mean that two routes with the same prefix and same label will be considered as identical which I am pretty sure would be wrong. The solution may be to remove the label from the index and add a new level to the tree with the label and if the label is zero then go through all the prefixes and remove them. This is not a small change, and is prone to mistake. I will therefore investigate more before performing the change.

**Comment by thomas-mangin** [comment] 2016-02-16 20:32
https://tools.ietf.org/html/rfc3107

    A BGP speaker can withdraw a previously advertised route (as well as
    the binding between this route and a label) by either (a) advertising
    a new route (and a label) with the same NLRI as the previously
    advertised route, 

This is what we do now.

    or (b) listing the NLRI of the previously
    advertised route in the Withdrawn Routes field of an Update message.

Does that mean that my understanding is wrong and tracking label is not required ?
Does this also mean that it would not be a violation if an implementation did not implement this second method.

    The label information carried (as part of NLRI) in the Withdrawn
    Routes field should be set to 0x800000.

/me is confused.

**Comment by tmmorin** [comment] 2016-02-19 09:08
BGP/MPLS are special in this respect: for the purpose of determining whether two routes are about the same NLRI or not, the Label is *not* considered part of the NLRI.

For instance a router can send an Update to change the label used for a said RD:Prefix; this will not be considered a new route by BGP.

In fact conceptually, the Label should be considered part of the nexthop information. But to allow more efficient packing of multiple prefixies in one BGP update in the case of many routes having same BGP attributes (e.g. routes of a same VPN having same Route Targets) but not having the same Label, the Label is encoded in the NLRI field.

Your understanding of RFC3107 is fine, and the fact that RFC2547/4364 are an exception to the rule is not obvious by reading the specs. I'll try to find the reference.

So for both (a) and (b), things should be implemented as if the Label was encoded outside of the NLRI.

**Comment by tmmorin** [comment] 2016-02-19 09:11
A related trick in RFC2547 is that for route withdraws the Label is supposed to be set to zero.  This is consistent with the interpretation that the Label should be considered part of the next-hop (and hence irrelevant for a withdraw)

**Comment by choisuibun** [comment] 2016-02-19 19:35
Hi Thomas

Withdrawing the labelled route with the advertised label can avoid the
problem on exabgp. It seems to be working with junos as well.

Thanks
Eric

**Comment by thomas-mangin** [comment] 2016-02-21 13:48
Thank you for the help but I am still unsure how to implement the change. In the scenario where a router announce a prefix with one label, then the same prefix with another label what would then be done by the router receiving them. Then what would happen if a withdraw with the first/second or no label is received (three cases) ?

**Comment by choisuibun** [comment] 2016-02-22 01:51
Hi Thomas. 

If r1 and r2 advertise the same label route to r3 with different label x and y respectively, r3 should advertise the best route unless add-path is there. 

R1 will not advertise the same with different label to r3 unless r1 is reboot or bgp session is bounced or previous route is withdrawn. R1 owns the label in the bgp label unicast and would not allocate two labels for the same route. 

Thanks
Eric

**Comment by tmmorin** [comment] 2016-02-22 08:53
@choisuibun : yes, it does not seem problematic that exabgp withdraws a VPN route without setting the label to zero. we don't need to change this behavior until we find an interop issue. 

@thomas-mangin : 
After the router announces "the same prefix with another label", the router receiving the announce consider that the route replaces the initially announced route for the same rd:prefix. Then "if a withdraw with the first/second or no label is received", in the three cases, it means that there is no route anymore for the RD:prefix.

So, the desired behavior in ExaBGP, is the following:
- when it receives from a neighbor an update of Label:RD:prefix, it needs to consider that it replaces any "*:RD:Prefix" route from this neighbor (any route with this RD and this prefix)
- when it receives from a neighbor a withdraw of Label:RD:prefix, it needs to consider that this withdraws any "*:RD:Prefix" route from this neighbor (any route with this RD and this prefix)

(reading again my messages above, it occurs to me that saying that RFC4364 is an exception to the rules in RFC3107 is wrong - the rules you quoted from RFC3107 are enough alone to mandate the behavior we are talking about)

**Comment by thomas-mangin** [comment] 2016-02-22 09:30
Thank you very much for the clarification. ExaBGP uses an hashmap/dict to track which routes where announced in its AdjRIBOut. It looks like its key does not need to use the label so the code should be changed as follow:

```
	def index (self, negotiated=None):
		addpath = 'no-pi' if self.path_info is PathInfo.NOPATH else self.path_info.pack()
		mask = chr(len(self.labels)*8 + len(self.rd)*8 + self.cidr.mask)
		return addpath + mask + self.labels.pack() + self.rd.pack() + self.cidr.pack_ip()
```
to 
```
		return addpath + mask + self.rd.pack() + self.cidr.pack_ip()
```

**Comment by tmmorin** [comment] 2016-02-26 09:03
Yes.

Note that we had to do something very similar for bagipe-bgp to have the proper behavior:
https://github.com/Orange-OpenSource/bagpipe-bgp/blob/use_upstream_exabgp/bagpipe/bgp/engine/ipvpn.py#L36

**Comment by thomas-mangin** [comment] 2016-02-26 09:27
Thank you @tmmorin - I will fix the code to reflect it.

**Comment by thomas-mangin** [comment] 2016-02-27 17:49
https://github.com/Exa-Networks/exabgp/commit/5ebd144153ed313b91a2856d202fa12dd25c397a

Some feedback would be appreciated as it may have some undesirable side effects. 
As the indexing does not take in consideration the label, if you announce label 1 and then withdraw label 2 - exabgp will see both route as similar and remove label 1 from the ADJ-RIB-OUT when generating the label 2 message on the wire.

From then on, it will ignore any more withdrawal for label 1 (as there is no more matching route in the RIB) until another route with a label is re-announced ...

Obviously this should not happen and would be a user error but still - I am not fully happy about it.

**Comment by thomas-mangin** [comment] 2016-03-20 10:46
Closing as no feedback as AFAIK the code is good.

**Closed by thomas-mangin** 2016-03-20 10:46 UTC
Labels: bug, fixed-need-testing, need-help
