### ISSUE TITLE
ExaBGP 3.4.13 announces withdrawn routes after reload

### ISSUE THREAD

**Issue by elfchief** [Exa-Networks/exabgp#370] opened 2016-02-03 20:52 UTC
I am having a problem where ExaBGP begins to announce withdrawn routes after it goes through a reload (via signal USR1). We have a subprocess watching the health of a service and sending "withdraw watchdog xxx" or "announce watchdog xxx" commands, and a static route in the exabgp config that should default to being withdrawn. The subprocess continues to send "withdraw" messages at regular intervals, though this does not withdraw the route after this problem occurs. Having the subprocess announce the watchdog and then withdraw it again _will_ remove the wayward route, however.

Reproduction steps:

(1) Start ExaBGP with a static route and an associated watchdog process (config snippet below)

(2) Verify that ExaBGP is not announcing the route (we verified this both by sending a 'show routes' command to ExaBGP, and looking at the upstream router). We can also verify that ExaBGP is receiving the withdraw messages via the logs:

```
    exabgp: 115241 processes     Command from process watchdog-service : withdraw watchdog watchdog-service
    exabgp: 115241 reactor       Performing dynamic route update
    exabgp: 115241 reactor       Updated peers dynamic routes successfully
```

(3) Reload ExaBGP ("service exabgp reload", which on our systems sends signal USR1; if I do a force reload via USR2, the same problem appears to happen, though I have not tested it extensively)

(4) Verify reload in log. Contains mostly expected messages about config parsing. Beyond the config file parsing, the remaining messages seem relatively as-expected:

```
     exabgp: 115241 reactor       Peer definition identical, updating peer routes if required for neighbor X.X.X.99 local-ip X.X.X.100 local-as XXXXX peer-as YYYYY router-id X.X.X.100 family-allowed in-open
     exabgp: 115241 reactor       Peer definition identical, updating peer routes if required for neighbor X.X.X.98 local-ip X.X.X.100 local-as XXXXX peer-as YYYYY router-id X.X.X.100 family-allowed in-open
     exabgp: 115241 configuration Loaded new configuration successfully
     exabgp: 115241 processes     Terminating process intmgr
     exabgp: 115241 processes     Forked process intmgr
     exabgp: 115241 processes     Terminating process watchdog-service
     exabgp: 115241 processes     Forked process watchdog-service
     exabgp: 115241 processes     Terminating process stats
     exabgp: 115241 processes     Forked process stats
```

(4.1) ExaBGP is also continuing to receive and process withdraw messages at this point:

```
    exabgp: 115241 processes     Command from process watchdog-service : withdraw watchdog watchdog-service
    exabgp: 115241 reactor       Performing dynamic route update
    exabgp: 115241 reactor       Updated peers dynamic routes successfully
```

(5) But ExaBGP is still announcing the route (we have a 'stats' process listening on port 1179 that just does 'show routes extensive' and passes the output back):

```
    $ nc localhost 1179
        neighbor neighbor X.X.X.99 local-ip X.X.X.100 local-as XXXXX peer-as YYYYY router-id X.X.X.100 family-allowed in-open Z.Z.Z.4/32 next-hop X.X.X.100
        neighbor neighbor X.X.X.98 local-ip X.X.X.100 local-as XXXXX peer-as YYYYY router-id X.X.X.100 family-allowed in-open Z.Z.Z.4/32 next-hop X.X.X.100
```

(5.1) Checking on the router itself confirms that these routes are actually being announced (this isn't just an error in the 'show routes extensive' output)

Our (sanitized) config file:

```
    group svc-service {
        hold-time 10;
        local-as XXXXX;
        peer-as YYYYY;
        router-id X.X.X.100;
        local-address X.X.X.100;

        family {
            ipv4 unicast;
        }

        capability {
            asn4 enable;
            route-refresh enable;
            graceful-restart 15;
        }

        process watchdog-service {
            run /etc/exabgp/processes/watchdog watchdog-service;
        }

        process stats {
            run /etc/exabgp/processes/stats;
        }

        static {
            route Z.Z.Z.4/32 {
                next-hop self;
                watchdog watchdog-service;
                withdraw;
            }
        }

        neighbor X.X.X.98 {
            description "upstream peer";
        }
        neighbor X.X.X.99 {
            description "upstream peer";
        }
    }
```

...help?

**Comment by thomas-mangin** [comment] 2016-02-04 10:18
Hello Jay, I think I can see why this is happening and the fix is not a one liner. Your issue provides me all the information I need to fix the problem. Please bare^Wbear with me while I fix the issue.

**Comment by elfchief** [comment] 2016-02-08 16:29
Much appreciated! Do let me know if there's anything I can do to assist/speed things along, given how potentially dangerous this bug is for us. I can arrange for beer if nothing else!

**Comment by thomas-mangin** [comment] 2016-02-08 20:54
Thank you for the offer - I will let you know if you need anything.

**Comment by thomas-mangin** [comment] 2016-02-27 18:16
A good fix would not be a small patch. would you mind if I only fixed it on master and not 3.4 ?

**Comment by elfchief** [comment] 2016-03-02 06:22
We just finished deploying a workaround making use of manual-eor, so we should be ok without an immediate patch available.

**Comment by thomas-mangin** [comment] 2016-03-02 18:05
Thanks - it remove some pressure to fix it.

**Comment by thomas-mangin** [comment] 2016-05-12 10:20
@elfchief This may be the solution to the problem. It prevent withdrawn routes when down to be announced on reconnection.
https://github.com/Exa-Networks/exabgp/commit/91bd87e8739611c27a5bb6be81144e3a5ee321e7

**Comment by thomas-mangin** [comment] 2016-05-12 10:23
I still need to investigate this - the watchdog code - which I wish I never wrote is not simple. I wonder if I should deprecate it for 4.0 ...

**Comment by brona** [comment] 2016-12-06 18:04
Hi any update for this for 4.0? I am using Erco together with ExaBGP and it seems I just hit this "feature".. deleted routes are not withdrawn after reload....

**Comment by jaroug** [comment] 2017-01-06 14:39
Hi,

We are curently experiencing this issue in production, version 3.4.13-1~bpo8+1 (debian). I was also able to reproduce the problem with a newer version (3.4.17-3).

Exabgp is used as routes injectors (/32) from loadbalancers to uplink firewalls then routers, from the quagga point of view the bgp session drop then is re-established but with 0 prefix announced.

Trying to dig around this issue I noticed that I wasn't able to reproduce this issue by reloading the configuration through a named pipe, following : https://github.com/Exa-Networks/exabgp/wiki/Controlling-ExaBGP-:-using-a-named-PIPE .

So we are going to use this workaround until this issue is resolved.

**Comment by thomas-mangin** [comment] 2017-05-29 11:44
Some work was done on master which I believe sort the issue but the back port is not clear (I did not write a few of the patches which I believe fixes the issue). Could you see if master does fix the issue and if so, then I would advise to use 4.0.1 when it is released.

**Comment by switchtower** [comment] 2017-11-14 15:13
I was able to reproduce this issue on 3.4.19
the config has 5044 routes for a specific community that we filter against:
`
cat conf_rtr.switchtower.com_ipv4.ini | grep 64512:318 -c
5044
`
 but on the router:
`
11.11.14.23     4 64512 37858694 1159621   771739    0    0    3d08h 5055
`
if I completely shutdown the process and start it back up, the number of routes are correct:
`
11.11.14.23     4 64512 37875815 1159308   771739    0    0 00:08:36 5044
`

**Comment by thomas-mangin** [comment] 2017-11-14 19:19
If possible, could you please look at 3.4.22 as I believe this issue may have been fixed with the patches in .21 and .22

**Comment by spakka** [comment] 2017-12-22 10:01
I had this issue, and moved to 3.4.23 and it seems to be fixed. A withdraw that happens when the peer is down, is now correctly reflected when the peer comes back up

**Comment by longmalx** [comment] 2018-04-13 10:51
Is there an update as to when this issue may be fixed in the 4.x release chain?
Builds from master are still showing this issue.

**Comment by longmalx** [comment] 2018-04-17 17:14
I have a rough patch which appears to fix the issue in 4.x - my problem is caused by backup_changes not being populated over reload. 

The old code that did this was removed between 3.4 and 4.x in the configuration file handling. 

I can submit a pull request with this fix, even though I’m not sure it’s the most elegant solution to the problem.

**Comment by longmalx** [comment] 2018-04-19 16:45
@thomas-mangin - I've create a PR #802 for the workaround

**Comment by thomas-mangin** [comment] 2018-11-19 17:38
closing as was fixed with the PR above

**Closed by thomas-mangin** 2018-11-19 17:38 UTC
Labels: bug
