### ISSUE TITLE
bgp link state capability

### ISSUE THREAD

**Issue by treemanzhou** [Exa-Networks/exabgp#562] opened 2017-01-05 07:04 UTC
Hi, exabgp developers 
   does exabgp support bgp-ls now ?

**Comment by treemanzhou** [comment] 2017-01-05 08:37
Thanks for your reply
   how can i run it ? this is my configuration file , but it didn't worked .

neighbor  10.16.255.10 {
        description "will announce a route until told otherwise";
        router-id 10.20.10.8;
        local-address 10.20.10.8;
        local-as 65200;
        peer-as 65200;

      process dump_to_file {
        run /root/exabgp/etc/exabgp/processes/syslog-1.py;
        encoder json;
        receive {
                parsed;
                update;
                neighbor-changes;
      }
    }  


here is the exception  
   Thu, 05 Jan 2017 16:28:37 | ERROR    | 15415  | configuration | problem with the configuration file, no change done
Thu, 05 Jan 2017 16:28:37 | ERROR    | 15415  | configuration | 
Thu, 05 Jan 2017 16:28:37 | ERROR    | 15415  | configuration | syntax error in section neighbor
Thu, 05 Jan 2017 16:28:37 | ERROR    | 15415  | configuration | line 7: process dump_to_file {
Thu, 05 Jan 2017 16:28:37 | ERROR    | 15415  | configuration | 
Thu, 05 Jan 2017 16:28:37 | ERROR    | 15415  | configuration | section process is invalid in neighbor, neighbor

**Comment by ruissalo** [comment] 2017-01-05 08:52
Give this a try and let me know
https://github.com/Exa-Networks/exabgp/wiki/BGP-LS-support

**Comment by treemanzhou** [comment] 2017-01-05 09:25
Raise error as
[Message header error / Unspecific / can not decode update message of type "2"]
and bgp negotiation stuck in open status

**Comment by treemanzhou** [comment] 2017-01-05 09:29
router isis 
distribute bgp-ls level 2 

IGP link stats seems propagated in bgp update message type 2 /

**Comment by ruissalo** [comment] 2017-01-05 09:51
Ok, I'm going to need more data to figure what the issue is. You seem to be using a Cisco device right? 
Can you send me the following:

full exabgp log stack after you start the exabgp intance
tcpdump capture with full packet size (-s0 option in tcpdump)
output of the isis database from the router

my addr is eveliovila at gmail.com
I'll take a look tomorrow.

Thanks

**Comment by treemanzhou** [comment] 2017-01-05 23:29
Hi thomas
   here is the log with the -d option. 
[log whit -d option.txt](https://github.com/Exa-Networks/exabgp/files/688663/log.whit.-d.option.txt)

**Comment by ruissalo** [comment] 2017-01-06 01:20
@thomas-mangin Can you review https://github.com/Exa-Networks/exabgp/pull/564 ?
Thanks!

**Comment by thomas-mangin** [comment] 2017-01-06 08:31
@ruissalo 

The capability is correctly negotiated, the bug is in your code

    return ', '.join(str(d) for d in self.ls_attrs)
  File "/root/exabgp/lib/exabgp/bgp/message/update/attribute/bgpls/link/rterid.py", line 28, in __repr__
    return "Remote TE Router ID: %s" % (self.terid.string)
AttributeError: 'IPv4' object has no attribute 'string'

I will look at it when I am on my laptop but I think the fix is simply to remove the .string

**Comment by ruissalo** [comment] 2017-01-06 09:04
Hi @thomas-mangin, you are correct, that's why I opened #564 (I think you skipped it in my comment) :)

**Comment by thomas-mangin** [comment] 2017-01-06 18:53
ok - fix merged closing.

**Closed by thomas-mangin** 2017-01-06 18:53 UTC
Labels: question
