### ISSUE TITLE
md5: Incorrect padding

### ISSUE THREAD

**Issue by nskalis** [Exa-Networks/exabgp#766] opened 2018-01-07 14:01 UTC
##### ISSUE TYPE

 - Bug Report

##### OS

```
$ hostnamectl
   Static hostname: nl-ams02c-ispbgp01.xxx.xxx
         Icon name: computer-vm
           Chassis: vm
        Machine ID: fe42ef15e88f89520e0946b6201079d0
           Boot ID: 54c23f2abe05477889261b29f5735a34
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.21.1.el7.x86_64
      Architecture: x86-64
```

##### VERSION

```
ExaBGP : 4.0.2-1c737d99
Python : 3.4.5 (default, Dec 11 2017, 14:22:24)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Uname  : Linux nl-ams02c-ispbgp01.xxx.xxxt 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64
Root   : /usr
```

##### ENVIRONMENT 

```
empty
```

##### CONFIGURATION

```
template {
		neighbor default {
				router-id 		xxxx ;
				local-address	xxx ;
				local-as 			xxx ;
				peer-as 			xxx ;
				hold-time 		180 ;
				group-updates false ;
		}
}

neighbor xxx {
		inherit 			default ;
		description 	"* xxx *" ;
		family	{
				ipv4 unicast ;
		}
		md5-password	xxx ;
}
```

##### SUMMARY

When installing ExaBGP via pip3 and trying to establish a BGP session (IP v4) and using `md5` (the password provided is clear text without quotes, not hashed) using the configuration above,
I am getting the following error (server-side):

##### STEPS TO REPRODUCE

```
$ exabgp --env /home/xxx/xxx/cfg/tpl/exabgp.rrdoc.ini /home/xxx/xxx/cfg/tpl/exabgp.rrdoc.xxx.cfg --debug
```
```
14:55:13 | 3398   | reactor       | ExaBGP version : 4.0.2-1c737d99
14:55:13 | 3398   | reactor       | Python version : 3.4.5 (default, Dec 11 2017, 14:22:24)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
14:55:13 | 3398   | reactor       | System Uname   : #1 SMP Thu May 25 17:04:51 UTC 2017
14:55:13 | 3398   | reactor       | System MaxInt  : 9223372036854775807
14:55:13 | 3398   | reactor       |         
14:55:13 | 3398   | reactor       |         
14:55:13 | 3398   | reactor       |         
14:55:13 | 3398   | reactor       |         
14:55:13 | 3398   | reactor       | <class 'binascii.Error'>
14:55:13 | 3398   | reactor       | Incorrect padding
14:55:13 | 3398   | reactor       | Traceback (most recent call last):
14:55:13 | 3398   | reactor       |   File "/usr/lib/python3.4/site-packages/exabgp/reactor/peer.py", line 527, in _run
14:55:13 | 3398   | reactor       |     for action in self._establish():
14:55:13 | 3398   | reactor       |   File "/usr/lib/python3.4/site-packages/exabgp/reactor/peer.py", line 314, in _establish
14:55:13 | 3398   | reactor       |     for action in self._connect():
14:55:13 | 3398   | reactor       |   File "/usr/lib/python3.4/site-packages/exabgp/reactor/peer.py", line 264, in _connect
14:55:13 | 3398   | reactor       |     connected = six.next(generator)
14:55:13 | 3398   | reactor       |   File "/usr/lib/python3.4/site-packages/exabgp/reactor/protocol.py", line 107, in connect
14:55:13 | 3398   | reactor       |     self.connection = Outgoing(afi,peer,local,self.port,md5,md5_base64,ttl_out)
14:55:13 | 3398   | reactor       |   File "/usr/lib/python3.4/site-packages/exabgp/reactor/network/outgoing.py", line 31, in __init__
14:55:13 | 3398   | reactor       |     MD5(self.io,self.peer,port,md5,md5_base64)
14:55:13 | 3398   | reactor       |   File "/usr/lib/python3.4/site-packages/exabgp/reactor/network/tcp.py", line 138, in MD5
14:55:13 | 3398   | reactor       |     md5 = base64.b64decode(md5)
14:55:13 | 3398   | reactor       |   File "/usr/lib64/python3.4/base64.py", line 90, in b64decode
14:55:13 | 3398   | reactor       |     return binascii.a2b_base64(s)
14:55:13 | 3398   | reactor       | binascii.Error: Incorrect padding
```
##### EXPECTED RESULTS

Establish the BGP session (with a JUNOS router).

##### ACTUAL RESULTS

Runtime error and traceback pasted above, related to md5.

##### IMPORTANCE

The BGP session is with a production vRR.

**Comment by nskalis** [comment] 2018-01-09 14:36
I forgot to describe how the peer is configured :)

```
> show configuration protocols bgp 
authentication-key "$9$xxx"; ## SECRET-DATA
...
group xxx {
    type internal;
    local-address xxx;
    passive;
    log-updown;
    import xxx;
    family inet {
        unicast;
    }
    export xxx;
    cluster xxx;
    neighbor xxx;
    neighbor xxx;
}
```

In other words, the md5 is configured at the TCP level.

**Comment by thomas-mangin** [comment] 2018-01-09 17:02
Thank you - someone else changed the MD5 code (need to go through blame .. sorry praise to find out who) and ask about this as I do not have a router at end to test ... I know I should created a lab and run more testing .. perhaps it is not too late for a 2018 resolution ...

**Comment by iwaseyusuke** [comment] 2018-01-17 01:27
I faced the similar issue, but the traceback message are a little different.

```
ExaBGP version : 4.0.2-1c737d99
Python version : 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
System Uname   : #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
System MaxInt  : 9223372036854775807


-- Traceback


Traceback (most recent call last):
  File "/usr/local/bin/exabgp", line 9, in <module>
    load_entry_point('exabgp==4.0.2', 'console_scripts', 'exabgp')()
  File "/usr/local/lib/python3.5/dist-packages/exabgp/application/__init__.py", line 13, in run_exabgp
    main()
  File "/usr/local/lib/python3.5/dist-packages/exabgp/application/bgp.py", line 300, in main
    run(env,comment,configurations,root,options["--validate"])
  File "/usr/local/lib/python3.5/dist-packages/exabgp/application/bgp.py", line 366, in run
    was_ok = Reactor(configurations).run(validate,root)
  File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/loop.py", line 131, in run
    if not self.load():
  File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/loop.py", line 318, in load
    self.listener.listen_on(ip, neighbor.peer_address, self._port, neighbor.md5_password, neighbor.md5_base64, None)
  File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/listener.py", line 100, in listen_on
    self._listen(local_addr, remote_addr, port, md5_password, md5_base64, ttl_in)
  File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/listener.py", line 64, in _listen
    MD5(sock,peer_ip.top(),0,md5,md5_base64)
  File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/network/tcp.py", line 165, in MD5
    md5_bytes = bytes_ascii(md5)
  File "/usr/local/lib/python3.5/dist-packages/exabgp/util/__init__.py", line 91, in bytes_ascii
    return bytes(bytestring, 'ascii')
TypeError: encoding without a string argument


-- Configuration





-- Logging History


00:33:56 | 226    | welcome       | Thank you for using ExaBGP
00:33:56 | 226    | version       | 4.0.2-1c737d99
00:33:56 | 226    | interpreter   | 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
00:33:56 | 226    | os            | Linux 3ef08f9dea7d 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64
00:33:56 | 226    | installation  | /usr/local
00:33:56 | 226    | advice        | environment file missing
00:33:56 | 226    | advice        | generate it using "exabgp --fi > /usr/local/etc/exabgp/exabgp.env"
00:33:56 | 226    | cli control   | named pipes for the cli are:
00:33:56 | 226    | cli control   | to send commands  /run/exabgp.in
00:33:56 | 226    | cli control   | to read responses /run/exabgp.out
00:33:56 | 226    | configuration | performing reload of exabgp 4.0.2-1c737d99
```

```
# exabgpd.conf

neighbor 172.17.0.2 {
    router-id 192.168.0.3;
    local-address 172.17.0.4;
    local-as 65002;
    peer-as 65000;
    md5-password "cGFzc3dk";  # base64 encoded value of "passwd"
}
```

I could avoid this traceback with the following;

```diff
$ git diff
diff --git a/lib/exabgp/util/__init__.py b/lib/exabgp/util/__init__.py
index 920f8cf..4860ada 100644
--- a/lib/exabgp/util/__init__.py
+++ b/lib/exabgp/util/__init__.py
@@ -88,4 +88,6 @@ if PY2:
                return string
 else:
        def bytes_ascii(bytestring):
+               if isinstance(bytestring, bytes):
+                       return bytestring
                return bytes(bytestring, 'ascii')
```

The given `bytestring` is already `bytes` type on Python3?
Just guessing, ExaBGP tries to **decode** `"cGFzc3dk"` --> `"passwd"` then pack `"passwd"` into binary?

**Comment by kbirkeland** [comment] 2018-01-26 13:13
So, the problem here is when `md5-password` is configured that there is actually another command called `md5-base64`.  In the case of `md5-base64` being unset, `MD5()` will attempt take your string and append equal signs until it base64 decodes.  I believe that behavior violates the principle of least astonishment and should be removed.  @thomas-mangin do you agree?  If so, what should the default behavior of `md5-base64` be - `True` or `False`?

As a stopgap for both of your issues above, if you set `md5-password` to the  plaintext password and `md5-base64` to `False`, then your configurations will work until this is fixed.

**Comment by thomas-mangin** [comment] 2018-01-26 14:15
.... changing behaviour ... hopefully 4.0 is not stable yet but yes, I see how I may have been trying too hard to be useful.

**Comment by nskalis** [comment] 2018-01-27 13:00
@kbirkeland @thomas-mangin thanks a lot guys for tackling this issue. any idea when the fix will be made available via `pip3` ?

**Comment by thomas-mangin** [comment] 2018-01-27 15:35
when I do the next release ... Just done two back to back .. if nothing change this week I will do a third.

**Comment by thomas-mangin** [comment] 2018-07-05 15:29
Does the change done for #838 resolve the issue ?

**Comment by thomas-mangin** [comment] 2019-05-23 11:45
https://github.com/Exa-Networks/exabgp/commit/21c2768dc0480fadd2b42b6f3f541eb324c22dae and 
https://github.com/Exa-Networks/exabgp/commit/8f7499eb1c1c72af2895f03806f0108f75621536 should help with this issue.

**Comment by thomas-mangin** [comment] 2019-08-27 10:35
As there was no feedback, I am closing the issue. Please feel free to re-open if you believe the issue is still present.

**Closed by thomas-mangin** 2019-08-27 10:35 UTC
Labels: bug, fixed-need-testing
