### ISSUE TITLE
Neighbor restart with large rib-out causes exabgp hang

### ISSUE THREAD

**Issue by adrian62** [Exa-Networks/exabgp#682] opened 2017-07-17 20:01 UTC
##### ISSUE TYPE
 - Bug Report

##### OS
Ubuntu 16.04 LTS

##### VERSION
```
ExaBGP : master-23528a149c326c20ad9ce87045b89c794958ef8e
Python : 2.7.11+ (default, Apr 17 2016, 14:00:29)  [GCC 5.3.1 20160413]
Uname  : Linux pocnjafx42 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64
Root   : /opt/exabgp_Releases/exabgp-23528a1

If run from outside the exabgp root folder:
ExaBGP : 4.0.1-4501ddf3
```

##### ENVIRONMENT 

```
[exabgp.api]
ack = false
 
[exabgp.log]
all = true
daemon = false
destination = 'stderr'
message = true
routes = true
 
[exabgp.tcp]
port = 11279
```

##### CONFIGURATION
```
template {
    neighbor GROUP_EXA_AFX_2_MISRR {
        family {
          ipv4 unicast;
          ipv6 nlri-mpls;
        }
        api {
              processes [ receive-routes ];
              receive {
                        parsed;
                        update;
              }
        }
    }
    neighbor GROUP_EXA_AFX_2_IAVRR {
        family {
          ipv4 mpls-vpn;
          ipv6 mpls-vpn;
        }
        api {
              processes [ inject-routes ];
              send {
                        update;
              }
              neighbor-changes;
        }
    }
}
 
process inject-routes {
       # get updates from pipe
         run /opt/AFX1.5/uafx.py;
         encoder json;
}
process receive-routes {
       # write updates into pipe
         run /opt/AFX/recRoute.sh /opt/AFX/RECV;
         encoder json;
}
 
neighbor 10.0.0.85 {
        inherit GROUP_EXA_AFX_2_MISRR;
        router-id 10.0.99.9;
        local-address 10.0.99.9;
        local-as 65060;
        peer-as 65060;
        adj-rib-in false;
        hold-time 90;

neighbor 10.0.99.4{
        inherit GROUP_EXA_AFX_2_IAVRR;
        router-id 10.0.99.9;
        local-address 10.0.99.9;
        local-as 65060;
        peer-as 65060;
        adj-rib-in false;
        hold-time 90;
        }
```

##### SUMMARY

Two peers are configured and they inherit from two different templates. The scripts alter routes received from peer 10.0.0.85 and push them to peer 10.0.99.4. The latter peer has rib-out enabled so that if it bounces the session the routes that had been previously advertised to it will be resent.
If the number of routes advertised to peer 10.0.99.4 is at 100K vpnv6 and 100K vpnv4 upon resetting peer 10.0.99.4 exabgp will make one attempt to reconnect and then will hang. The condition causes keepalives to stop going out from exabgp to the peers, such that after 90 seconds both peers are down and the exabgp logs are at that point completely quiet.

##### STEPS TO REPRODUCE

Upon clearing the session from the peer with the large rib-out exabgp will hang, sample log below.
```
Jul 17 15:27:35 pocnjafx85 exabgp[98226]: outgoing-1    >> KEEPALIVE
Jul 17 15:27:49 pocnjafx85 exabgp[98226]: outgoing-5    >> KEEPALIVE
Jul 17 15:27:52 pocnjafx85 exabgp[98226]: outgoing-1    << KEEPALIVE
Jul 17 15:27:54 pocnjafx85 exabgp[98226]: outgoing-5    << KEEPALIVE
Jul 17 15:28:05 pocnjafx85 exabgp[98226]: outgoing-1    >> KEEPALIVE
Jul 17 15:28:11 pocnjafx85 exabgp[98226]: outgoing-5    << NOTIFICATION
Jul 17 15:28:11 pocnjafx85 exabgp[98226]: outgoing-5    peer reset, message [notification received (6,4)] error[Cease / Administrative Reset]
Jul 17 15:28:14 pocnjafx85 exabgp[98226]: outgoing-6    connection to 10.0.0.83 closed
Jul 17 15:28:18 pocnjafx85 exabgp[98226]: outgoing-1    << KEEPALIVE
Jul 17 15:28:18 pocnjafx85 exabgp[98226]: outgoing-7    >> OPEN version=4 asn=65060 hold_time=90 router_id=10.0.99.19 capabilities=[Multiprotocol(ipv4 mpls-vpn,ipv6 mpls-vpn), ASN4(65060)]
Jul 17 15:28:18 pocnjafx85 exabgp[98226]: outgoing-7    << OPEN
Jul 17 15:28:18 pocnjafx85 exabgp[98226]: outgoing-7    << OPEN version=4 asn=65060 hold_time=180 router_id=10.0.0.83 capabilities=[Multiprotocol(ipv4 mpls-vpn,ipv6 mpls-vpn), Route Refresh, Unknown 5, Graceful Restart Flags 0x0 Time 120 , ASN4(65060), Unassigned 71, Route Refresh]
Jul 17 15:28:18 pocnjafx85 exabgp[98226]: outgoing-7    >> KEEPALIVE (OPENCONFIRM)
Jul 17 15:28:18 pocnjafx85 exabgp[98226]: outgoing-7    << KEEPALIVE
Jul 17 15:28:18 pocnjafx85 exabgp[98226]: network       Connected to peer neighbor 10.0.0.83 local-ip 10.0.99.19 local-as 65060 peer-as 65060 router-id 10.0.99.19 family-allowed in-open
```

no logs received from exabgp after this attempt at reconnecting. A bit of feedback from testers: in previous versions the KEEPALIVE logs identified the peer by IP address, now one has to walk back the log to see which "outgoing" corresponds to which peer.

##### EXPECTED RESULTS
session re-establishes and routes are resent. Verified to be working up to a scale of 10K v4 and 10K v6.

##### ACTUAL RESULTS
Hung

##### IMPORTANCE
Prevents successfully  completing QA (and deployment of this application to a production environment is not feasible).

**Comment by adrian62** [comment] 2017-07-20 20:48
Right, with 10k+10k it works as expected for us.

Adrian

**Comment by thomas-mangin** [comment] 2017-07-20 20:49
ack. will increase and look at what cause the issue.

**Comment by thomas-mangin** [comment] 2017-07-20 22:54
pushed some improvements/fixes but not the one I think affected you .. I could not replicate any freeze at 100k but my routes where just IP + next-hop .. but it was sure taking some CPU ...

updated initial request as some information was hidden as comment. 
 - any reason why are you not running ExaBGP twice, one per peer ? Python is limited to a single core, you will double the performance by using two instances.

I will check the behaviour of ExaBGP on reception of 6.4 as I only tested closing TCP today (and ran out of time for more checks).

**Comment by adrian62** [comment] 2017-07-21 16:01
Originally we ran one exabgp per peer, but we found advantages to using a single instance.
In any case, we reverted to separate instances per peer and the result is the same: the instance maintaining the rib-out never recovers from a peer bounce event.
Let me know if we can provide any diagnostic data.

**Comment by thomas-mangin** [comment] 2017-07-21 17:01
knowing you see the issue with one peer only is useful, I will continue my investigation.

**Comment by adrian62** [comment] 2017-07-25 07:39
I have recreated this issue in my more isolated environment and was looking to find the breakpoint. In this particular test bed, the problem manifests at 98000 routes (combined v4 and v6). What I have observed is that upon the peer restart exabgp becomes very busy, utilizing 100% of its CPU. If I drop the number of routes to 82000 the peering session survives but it takes a long time to recover and resend the routes to the peer.

**Comment by thomas-mangin** [comment] 2017-07-25 08:15
@adrian62 I have not forgotten this issue, I am just going on holidays next week and need to close a number of action points before I go. I am therefore quite busy and do not have as much free/personal time as I would like to investigate. I have an idea on what could cause it - I just need more time to check my itch.

**Comment by adrian62** [comment] 2017-09-26 15:48
Circling back on this issue, for a while I thought this is related to #704 but it's not; or more accurately the fix for #704 is not addressing the problem reported here.

**Comment by thomas-mangin** [comment] 2017-09-29 13:21
ack.

**Comment by thomas-mangin** [comment] 2017-10-16 19:45
Any change to get a env which produce the issue ?

**Comment by adrian62** [comment] 2017-10-18 15:02
Hi Thomas,
I can probably get something going; but I would prefer deferring this issue in favor of another that we discussed at times but for which there is no open ticket.That is the performance of exabgp with rib disabled.
My project is a kind of SDN controller that ends up processing large numbers of routes, on the order of the internet table plus some.When i first started we ran with 3.4.19 and we could push through the API somewhere in the 1500-2000 routes per second.When we ran into some issues and you suggested the 4.0 code we saw a performance drop, even after you refactored the RIB code.The code we presently use, commit <d337e15> processes around 500-700 routes per second which is fine for a small application like DDOS mitigation. After that commit the performance dropped to about 150, and it went back up some with the Oct 16th commit.Since there is no rib there is no state to be kept (aside from the peers), and I am hoping that the performance can be improved substantially to levels of the 3.4.19 and beyond. I am really hoping we can push it up to many thousands, if this SDN controller is to succeed running a large ISP like us.
How do we go about this? Should I open a ticket? Do you want us to profile a specific code commit and use that as a starting point? Let me know your thoughts.
thanksadrian
    On Monday, October 16, 2017, 12:45:29 PM MST, Thomas Mangin <notifications@github.com> wrote:  
 
 
Any change to get a env which produce the issue ?

**Comment by itsuugo** [comment] 2017-11-23 09:11
Hi @thomas-mangin 

I think that I'm facing the same issue, I'm using https://github.com/spotify/super-smash-brogp to inject routes with exabgp version 4.0.2.
Exabgp hangs after the routes injected are more than 13k (I can't confirm that's the exact number, but it uses to happen around it). 
I ran it in foreground with debug but there are nothing meaningful  in the log. Also, sending `Ctrl+C` can't kill it, it shows messages that the reactor try to shutdown but nothing happens.

I installed exabgp version 3.4.22 and everything is working fine.

**Comment by thomas-mangin** [comment] 2018-01-11 23:44
@aojea - if all os good, I will close the issue 😉

**Comment by thomas-mangin** [comment] 2018-01-15 10:02
I have informed "off-github" that I should not close the issue as not fixed - so re-opening

**Comment by 4mig4** [comment] 2018-06-11 02:13
thomas what is the status of this issue ? is the github reflecting the correct status ?

**Comment by thomas-mangin** [comment] 2018-06-11 10:21
There was a change to master which may have fixed the issue ... the issue is not closed as it is not sure.

**Comment by aecro** [comment] 2018-12-03 18:36
Hey,
I'm hitting the same issue with super-smash-brogp and ExaBGP 4.0.8-793a2931. I've done some troubleshooting. 

So with the default settings of that script, it announces 10000 routes initially, then waits a bit, then enters a loop which announces a random amount between 5000 and 7000 routes and then withdraws 1% of the announced routes. With these settings the initial announce works and exabgp freezes during the first update in the loop. At that point my router has received ~12500 routes.

First thing I noticed is, that even though the initial announce sends 10000 routes the router only receives ~9950 routes, which made me think that exabgp can't handle all the messages in quick succession. However, when I added a time.sleep(0.01) after every announcement, it was still dropping some routes and freezing after the router received ~13000 routes.

I then reduced the initial announcement to 1000 routes (while keeping the sleep(0.01)), my router was showing 994 routes. I also limited the further updates to adding only 500 routes and exabgp froze after my router was showing ~10500 routes.

Before those tests I accidentally put an error into the script which made it crash after the initial announce of 10000 routes (this was without the sleep(0.01)), so exabgp kept restarting the script and was sending 10000 random routes over and over again. Weirdly, when doing this, exabgp doesn't freeze and I was able to get up to ~500k routes, before my router ran out of memory.

I hope this helps tracking down the issue, let me know if you need anything else.

**Comment by thomas-mangin** [comment] 2018-12-04 07:42
code MUST flush stdout and super-smash-brogp does not. Sent them a patch to fix the issue.

**Closed by thomas-mangin** 2018-12-04 07:42 UTC
Labels: bug

**Comment by 4mig4** [comment] 2018-12-04 07:56
Merci beaucoup monsieur ! :)

**Comment by aecro** [comment] 2018-12-04 09:22
Mkay, so the flushing takes care of ExaBGP dropping single routes, I can confirm that's working. After the initial update, my router has received exactly 10000 routes, but again, during the second update, exabgp freezes after my router has received ~12600 routes.
