### ISSUE TITLE
ExaBGP fails parsing AS4_PATH attribute on an AS2 session

### ISSUE THREAD

**Issue by spakka** [Exa-Networks/exabgp#353] opened 2015-11-25 16:06 UTC
Hi Thomas,

I came across a weird problem that was causing one of our BGP sessions to continually die and then restart, and flap endlessly.

Situation:
Our ExaBGP advertises AS4 capability. Peer does not. Therefore this should be NEW -> OLD speaker situation (RFC6793).
The peer has received a BGP update from an upstream. Since the peer only supports AS2, the upstream sends the AS4_PATH attribute (optional, transitive) with some AS4s in the path, which our peer then passes on to us.
However, with this particular peer, every time ExaBGP sees a AS4_PATH attribute, it fails with a packet decode error, sends a Notify and tears down the session.

Example debug output:
```
Nov 25 15:27:21 rrc20 exabgp 40619  wire          session 1 outgoing 2001:7f8:24::fd / 2001:7f8:24::9 RECEIVED  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0076 02
Nov 25 15:27:21 rrc20 exabgp 40619  wire          session 1 outgoing 2001:7f8:24::fd / 2001:7f8:24::9 RECEIVED  (247) 0000 005F 4001 0100 4002 0C02 0573 FB1B 1B32 9C28 BD5B A0C0 1116 0205 0000 73FB 0000 1B1B 0000 329C 0000 28BD 0004 091E 800E 3000 0201 2020 0107 F800 2400 0000 0000 0000 0000 AAFE 8000 0000 0000 0002 2438 FFFE A4A9 0700 2028 0420 3821 2804 2038 80
Nov 25 15:27:21 rrc20 exabgp 40619  message       Peer  2001:7f8:24::9 ASN 29691   << UPDATE
Nov 25 15:27:21 rrc20 exabgp 40619  parser        parsing flag 40 type 01 (origin) len 01 payload  (2) 00
Nov 25 15:27:21 rrc20 exabgp 40619  parser        parsing flag 40 type 02 (as-path) len 0c payload  (29) 0205 73FB 1B1B 329C 28BD 5BA0
Nov 25 15:27:21 rrc20 exabgp 40619  parser        parsing flag c0 type 11 (as4-path) len 16 payload  (54) 0205 0000 73FB 0000 1B1B 0000 329C 0000 28BD 0004 091E
Nov 25 15:27:21 rrc20 exabgp 40619  message       Peer  2001:7f8:24::9 ASN 29691   Could not decode message "2"
Nov 25 15:27:21 rrc20 exabgp 40619  message       Peer  2001:7f8:24::9 ASN 29691   type object 'AS4Path' has no attribute '_AS4Path__new_aspaths'
Nov 25 15:27:21 rrc20 exabgp 40619  wire          session 1 outgoing 2001:7f8:24::fd / 2001:7f8:24::9 SENDING  (154) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 003E 0301 0063 616E 206E 6F74 2064 6563 6F64 6520 7570 6461 7465 206D 6573 7361 6765 206F 6620 7479 7065 2022 3222
Nov 25 15:27:21 rrc20 exabgp 40619  message       Peer  2001:7f8:24::9 ASN 29691   >> NOTIFICATION (1,0,"can not decode update message of type "2"")
Nov 25 15:27:21 rrc20 exabgp 40619  network       Peer  2001:7f8:24::9 ASN 29691   out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
Nov 25 15:27:21 rrc20 exabgp 40619  wire          session 1 outgoing, closing connection from 2001:7f8:24::fd to 2001:7f8:24::9
```

P.S. it reliably does this over both IPv4 and IPv6 sessions. And I think we have only seen it on this one peer, because most of our peers are AS4 capable. Also, this is version 3.4.12 with the patch for issue 337 applied.

I've emailed you the PCAP and full debug output for a particular session in case you need more details.

If you need any further info, just let me know.

Thanks!
Colin

**Comment by thomas-mangin** [comment] 2015-11-25 16:27
I will investigate.

**Comment by thomas-mangin** [comment] 2015-11-25 19:14
I have the feeling that it is a duplicate of issue #331 - could you please check if this patch https://github.com/Exa-Networks/exabgp/commit/8ff7dc071bce2dd4524ad484d84117ced9e876bc now in 3.4 stable fixes it.

**Comment by spakka** [comment] 2015-11-26 09:07
Thanks, will try it out today and let you know

**Comment by spakka** [comment] 2015-11-26 10:43
Yep, it fixes it. Thanks for that!

**Comment by thomas-mangin** [comment] 2015-11-26 12:27
Great :-)

**Closed by thomas-mangin** 2015-11-26 12:27 UTC
Labels: bug
