### ISSUE TITLE
Python error for exabgp master ./sbin/exabgp: line 40: : command not found

### ISSUE THREAD

**Issue by rushikeshjadhav** [Exa-Networks/exabgp#717] opened 2017-09-17 07:34 UTC
##### ISSUE TYPE
 - Bug Report

##### OS
CentOS7 

##### VERSION 
master / 4.0.2
```
[root@rishi2 exabgp(keystone_admin)]# git clone https://github.com/Exa-Networks/exabgp.git

[root@rishi2 exabgp(keystone_admin)]# cd exabgp

[root@rishi2 exabgp(keystone_admin)]# git checkout 3.4

[root@rishi2 exabgp(keystone_admin)]# ./sbin/exabgp --version
ExaBGP : 3.4.20
Python : 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Uname  : #1 SMP Wed May 13 10:06:09 UTC 2015

[root@rishi2 exabgp(keystone_admin)]# git branch
* 3.4
  master

[root@rishi2 exabgp(keystone_admin)]# git checkout master
Switched to branch 'master'

[root@rishi2 exabgp(keystone_admin)]# ./sbin/exabgp --version
./sbin/exabgp: line 40: : command not found
./sbin/exabgp: line 42: exec: : not found
```
##### ENVIRONMENT 
Empty output
```
[root@rishi2 exabgp(keystone_admin)]# ./sbin/exabgp --di
./sbin/exabgp: line 40: : command not found
./sbin/exabgp: line 42: exec: : not found
[root@rishi2 exabgp(keystone_admin)]# git checkout 3.4
Switched to branch '3.4'
[root@rishi2 exabgp(keystone_admin)]# ./sbin/exabgp --di
[root@rishi2 exabgp(keystone_admin)]#
```
##### SUMMARY

Unable to run 4.0.2

##### STEPS TO REPRODUCE

```
[root@rishi2 exabgp(keystone_admin)]# git clone https://github.com/Exa-Networks/exabgp.git

[root@rishi2 exabgp(keystone_admin)]# cd exabgp

[root@rishi2 exabgp(keystone_admin)]# git checkout 3.4

[root@rishi2 exabgp(keystone_admin)]# ./sbin/exabgp --version
ExaBGP : 3.4.20
Python : 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Uname  : #1 SMP Wed May 13 10:06:09 UTC 2015

[root@rishi2 exabgp(keystone_admin)]# git branch
* 3.4
  master

[root@rishi2 exabgp(keystone_admin)]# git checkout master
Switched to branch 'master'

[root@rishi2 exabgp(keystone_admin)]# ./sbin/exabgp --version
./sbin/exabgp: line 40: : command not found
./sbin/exabgp: line 42: exec: : not found
```

**Comment by thomas-mangin** [comment] 2017-09-17 15:01
try to run: `find . -name "*pyc" -exec rm {} \;` to make sure you are not mixing compiled python files between version and  then find which package on `centos` provides the `exec` program.

This is not a bug with exabgp and I am not sure how you can have an error on line 40 when the ./sbin/exabgp script is only 20 lines long.

```
$ git branch
* 3.4
  master
  py3

$ wc -l ./sbin/exabgp
20 ./sbin/exabgp
```

**Comment by rushikeshjadhav** [comment] 2017-09-18 11:16
Hello Thomas,

It seems you checked the version 3.4 which is also working correctly for me.

The one that is failing is master branch

[root@rishi2 exabgp]# git branch
* 3.4
  master
[root@rishi2 exabgp]# wc -l ./sbin/exabgp
20 ./sbin/exabgp
[root@rishi2 exabgp]# git checkout master
Switched to branch 'master'
[root@rishi2 exabgp]# wc -l ./sbin/exabgp
42 ./sbin/exabgp
[root@rishi2 exabgp]# ./sbin/exabgp --version
./sbin/exabgp: line 40: : command not found
./sbin/exabgp: line 42: exec: : not found
[root@rishi2 exabgp]#

**Comment by thomas-mangin** [comment] 2017-09-18 11:24
```
12:22 $ git branch
  3.4
* master
  py3

12:22 $ wc -l ./sbin/exabgp
42 ./sbin/exabgp

12:22 $ ./sbin/exabgp --di

```
You need to make sure you have `exec` installed in you path

**Comment by thomas-mangin** [comment] 2017-09-18 21:58
If you have no `exec`: you can try to edit the file and remove the word `exec` or use `sh` instead - should work but you will not get the return code if there is an error.

**Comment by vincentbernat** [comment] 2017-09-19 05:04
`exec` is a shell builtin. From the command, it is looking for `exec: :` and `: command`. Maybe `/bin/sh` is not a POSIX shell. Does `bash ./sbin/exabgp` works better?

**Comment by rushikeshjadhav** [comment] 2017-09-19 05:45
Following are the outputs

[root@rishi2 exabgp-4.0.2]# ./sbin/exabgp --version
./sbin/exabgp: line 40: : command not found
./sbin/exabgp: line 42: exec: : not found

[root@rishi2 exabgp-4.0.2]# bash ./sbin/exabgp --version
./sbin/exabgp: line 40: : command not found
./sbin/exabgp: line 42: exec: : not found

[root@rishi2 exabgp-4.0.2]# sh ./sbin/exabgp --version
./sbin/exabgp: line 40: : command not found
./sbin/exabgp: line 42: exec: : not found

### Changed exec to bash ###
[root@rishi2 exabgp-4.0.2]# vim ./sbin/exabgp
[root@rishi2 exabgp-4.0.2]# ./sbin/exabgp --version
./sbin/exabgp: line 40: : command not found
bash: : No such file or directory
[root@rishi2 exabgp-4.0.2]#

**Comment by rushikeshjadhav** [comment] 2017-09-19 06:21
for INTERPRETER in "$INTERPRETER" python3 pypy3; do
    INTERPRETER="$(command -v "$INTERPRETER")" && break
done


^^ Does this need python3 to run? It seems my system does not have it and using python2.7

**Comment by vincentbernat** [comment] 2017-09-19 06:34
Try:

```
echo $IFS
sh -x ./sbin/exabgp --version
```

**Comment by vincentbernat** [comment] 2017-09-19 06:40
Oh, you are right, the error message is not clear, but it means INTERPRETER is empty (I get "permission denied" on my side, but maybe it depends on the shell).

**Comment by rushikeshjadhav** [comment] 2017-09-19 06:54
Understood.. I think this requirement of python3 should have been mentioned somewhere. I'll try it with python3 later and report back. Cant break the current system :)

**Comment by thomas-mangin** [comment] 2017-09-19 07:54
You CAN run 4.0 with python 2 but the support will be dropped at some point, and most OS now come with python3 installed by default. If you just add your python2 to the list of interpreters it will work.

That was a funny one, I will add some code to report if no interpreter could be found !

**Comment by rushikeshjadhav** [comment] 2017-09-19 08:00
Thanks.

I changed as following
for INTERPRETER in "$INTERPRETER" python python3 pypy3; do
    INTERPRETER="$(command -v "$INTERPRETER")" && break
done

And it seem to have worked.

[root@rishi2 exabgp-4.0.2]# ./sbin/exabgp --version
ExaBGP : 4.0.2-1c737d99
Python : 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Uname  : Linux rishi2 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64
Root   : /root/source/exabgp/exabgp-4.0.2

Would there be any issue if I run exabgp-4.0.2 with python2? Apart from support drop.

**Comment by thomas-mangin** [comment] 2017-09-19 08:04
Added some information on the homepage regarding python version and changed the script to warn users when python3 is missing.

What you done does work ATM, and hopefully no python2 only bug exists in the code. It would be better if you could install python3 - but updating would create a conflict in your file - I will add an option to add python2 list of INTERPRETER ...

**Comment by thomas-mangin** [comment] 2017-09-19 08:05
Sorry you can already, you should instead do this (instead of modifying the file)
`INTERPRETER=python ./sbin/exabgp`

**Comment by thomas-mangin** [comment] 2017-09-19 08:08
Regarding support - currently ExaBGP is BOTH a python2 and python3 program (do not tell users that tho - they might not install python3 :p).

I will support both interpreter but I intend to drop support for python2 before 2020. Most likely the version will jump from 4.0 to 5.0 when I do so it will be obvious.

**Comment by rushikeshjadhav** [comment] 2017-09-19 08:43
Wonderful. Thank you. Great work!

I'm using this on my neutron server and would raise if anything specific to ExaBGP comes.

**Comment by chantra** [comment] 2017-09-19 14:29
Just adding a datapoint here... i am using exabgp with
`INTERPRETER=python2.7 /path/to/exabgp` and it is working fine for our
*limited* use case.

IIRC, the only reason I do this is because of an error with exabgpcli
(which i yet have to debug/fix/file but could not prioritize) which I could
work around that way.
Thanks for the effort in moving to py3 and I will try from my side to debug
and report back :)

**Comment by chantra** [comment] 2017-09-19 16:24
ok, got over my procrastrination. py3 compatible exabgpcli in PR #719

**Closed** 2017-09-19 17:50 UTC
Labels: bug, resolved
