### ISSUE TITLE
exabgp ibgp down

### ISSUE THREAD

**Issue by BeyongSpringWater** [Exa-Networks/exabgp#391] opened 2016-03-21 02:32 UTC
```
exabgp: 29770  network       Peer  ip1 ASN asnumber out loop, peer reset, message [] error[]
exabgp: 29770  message       Peer  ip2 ASN asnumber<< KEEPALIVE
exabgp: 29770  message       Peer  ip2 ASN asnumber << NOTIFICATION

********************************************************************************
EXABGP MISBEHAVED / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP, as the problem only affects one
peer, we are trying to keep the program running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************


ExaBGP version : 3.4.13
Python version : 2.6.6 (r266:84292, May 29 2014, 05:49:27)  [GCC 4.4.6 20110731 (Red Hat 4.4.6-3)]
System Uname   : #1 SMP Mon Jan 28 17:12:52 CST 2013
System MaxInt  : 9223372036854775807


peer ip2 ASN asnumber

<type 'exceptions.KeyError'>
3
Traceback (most recent call last):
  File "/home/work/agentInstall/sh.a1_sender01/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/peer.py", line 587, in _run
    for action in self._main(direction):
  File "/home/work/agentInstall/sh.a1_sender01/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/peer.py", line 456, in _main
    for message in proto.read_message():
  File "/home/work/agentInstall/sh.a1_sender01/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/protocol.py", line 168, in read_message
    self.peer.reactor.processes.message(msg_id,self.peer,message,'','')
  File "/home/work/agentInstall/sh.a1_sender01/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/api/processes.py", line 270, in closure
    return function(self,*args)
  File "/home/work/agentInstall/sh.a1_sender01/exabgpAgent/newlyExabgp/exabgp/lib/exabgp/reactor/api/processes.py", line 306, in message
    self._dispatch[message_id](self,peer,message,header,*body)
KeyError: 3
```

**Comment by BeyongSpringWater** [comment] 2016-03-21 02:34
excuse me，what can i do？

**Comment by thomas-mangin** [comment] 2016-03-28 13:12
This looks like a duplicate of #392, could you please check if 3.4.16 does fix the issue ?

**Closed** 2016-03-28 13:14 UTC
Labels: duplicate, fixed-need-testing
